##Show alignment of HHblits search of human CFAP53_residue 33-119.

cat "/home/kensch/Alignments/A3M files/ELLEn/ELLEn_query_msa.a3m"
#A3M#
>Q_cfap53_nt_minim_1
AEHHLERIRRSHQKHNAILASIKSSERDRLKAEWDQHNDCKILDSLVRARIKDAVQGFIINIEERRNKLRELLALEENEYFTEMQLK
>UniRef100_UPI0006D8F02E cilia- and flagella-associated protein 53 n=1 Tax=Latimeria chalumnae TaxID=7897 RepID=UPI0006D8F02E
IDieLQLQR--LREAADRKLLAFAKYRQNCEFKCEWEKMTDRRVVQGVIERRVHDSMQQYKMGLEERRQRLQDLLGAEEREYLKEMDSM
>UniRef100_A0A1A8BTT5 Coiled-coil domain containing 11 (Fragment) n=1 Tax=Nothobranchius kadleci TaxID=1051664 RepID=A0A1A8BTT5_9TELE
PNYQFLQERRREAVRGQLLDYKKDIGNCDVKTSLFESSKHHYVRKAVERRVGADRQQHQAQINQRRCRFKQTLETEKEQLLQEMKDK
>UniRef100_A0A091RYG8 Coiled-coil domain-containing protein 11 (Fragment) n=2 Tax=Nestor notabilis TaxID=176057 RepID=A0A091RYG8_NESNO
NDNFVLAWRQKEKELLENTNLIKLFDQYCKVYRWQQHKEQKWLHSDVQRKVNATMQEYLARIDERRARLCELLDAEESRYCAEMEAL
>UniRef100_A0A3Q0D103 Cilia- and flagella-associated protein 53 n=1 Tax=Mesocricetus auratus TaxID=10036 RepID=A0A3Q0D103_MESAU
AEQGFKRILPDGSACILAVPS------------WSCLAPYGFLHFLCPGGV----------------HLGCLVFLSPVHYWVDMP--
>UniRef100_A0A670ZS24 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Pseudonaja textilis TaxID=8673 RepID=A0A670ZS24_PSETE
------MLATLSLGDFNSQNSPASKLESKLAGEFWELKSSRLKVANLDFKIKPNCISFLF-------RLRDLLETEEKGFIAEMESQ
>UniRef100_A0A7K4YAK1 CFA53 protein (Fragment) n=1 Tax=Bucorvus abyssinicus TaxID=153643 RepID=A0A7K4YAK1_BUCAB
SESLFSASRQKEQELLENAQLLKLYNRCRNLYEWQQRKEQKWLHSAVQRKVAATMREYQAGMEERRERLRDLLEVEEKSLLAEIEAL
>UniRef100_A0A7K6AJE7 CFA53 protein (Fragment) n=1 Tax=Upupa epops TaxID=57439 RepID=A0A7K6AJE7_UPUEP
RCDSAAADRRKEEELQEIAASLRLHDQRCDVLQWHQRGRHRWLHRARRREVEAATQEYLQGIEERRERLRELLQAEESSYLAEMKKF
>UniRef100_A0A7K6DXG3 CFA53 protein (Fragment) n=1 Tax=Grantiella picta TaxID=266360 RepID=A0A7K6DXG3_9PASS
IEEAIFAERVREEERRKQDEALQVFSHYRNACDWHKEGEEKWMHRAAERKAWEAVQEYLEEINVRRERLRDFLEAEENRHFAEVVAL
>UniRef100_A0A8B9P0E6 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Apteryx owenii TaxID=8824 RepID=A0A8B9P0E6_APTOW
REKLVLARRQKEEERLKYVDFSMLYSKYHNINEWQEQSDRRRLHNSIQRRVEETMQVYLAETEDRRERLRELLESEEKRYFAEMESL
>UniRef100_A0A8C0VCZ3 Cilia and flagella associated protein 53 n=1 Tax=Cyanistes caeruleus TaxID=156563 RepID=A0A8C0VCZ3_CYACU
VEEAILAERVQQEEQCEQERDLRVFWHYRNACDWHKSGEDKWLHRTAERKVRETLQQYLQEIDVRRERLRDFLEAEESRHFAEVEAL
>UniRef100_F7F411 Trichohyalin-plectin-homology domain-containing protein n=2 Tax=Ornithorhynchus anatinus TaxID=9258 RepID=F7F411_ORNAN
RDHDVLKSRHDEQIFAANLASMKKTEQQCLKNEWQRHSDRRIFNKSLQMKVDQAMQGVLMDTEARRERLRELLAAEEKEFFVEMESK
>UniRef100_UPI0023047EAA cilia- and flagella-associated protein 53 n=1 Tax=Hemicordylus capensis TaxID=884348 RepID=UPI0023047EAA
AGKQILAWRAQDKIRHEAAMYAKAHLLGCQINEREHHTERKMLLRRVQERVDTEMQAYLAGAEERKERLRDLLEAEEKCYIAEMESL
>UniRef100_A0A1S3IG99 Cilia- and flagella-associated protein 53 n=1 Tax=Lingula unguis TaxID=7574 RepID=A0A1S3IG99_LINUN
PEHLILERRKKEEMREEALHQTKYNEFCDLKNDWERWTDRRIQINTVKRKVAGLMQAEQFGIEDRREKLRDLLMEEEQQYLKEMEEK
>UniRef100_A0A1X7U302 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Amphimedon queenslandica TaxID=400682 RepID=A0A1X7U302_AMPQE
KEHLILETRKQHKLREEAEAIVSYNKQFDLKTTWENETDAKLKRNTIKRRVEHLMQQRQYSLEERRDKLRALLQSEEEQYMSEIAVK
>UniRef100_A0A267DJG8 Trichohyalin-plectin-homology domain-containing protein (Fragment) n=1 Tax=Macrostomum lignano TaxID=282301 RepID=A0A267DJG8_9PLAT
GDWIIQQSREEAARRAERDAEVRAQALMDMRSDWEQQTNKRLQRKAVNRRLQEYRRQMEMRIEERRDRLRALLEADERRHLEEMDAS
>UniRef100_A0A2C9JT13 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Biomphalaria glabrata TaxID=6526 RepID=A0A2C9JT13_BIOGL
PDWLVMKNRETEERIKALQFEVKDQHMRNIRTDFETSGDKKFLQLNIRSRIQSLTKANEYNLECRREKLRNLFELEEANYLKEMDEQ
>UniRef100_A0A2T7PWI6 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Pomacea canaliculata TaxID=400727 RepID=A0A2T7PWI6_POMCA
ADFLILERKKQEDAREEMLKQTMIYQLNDLKTEWERNSDRRLMLKNINREVDNRLKINEFTVEDRRERLRELLRREEQEYIAEMEAA
>UniRef100_A0A3M7PHX5 Cilia-and flagella-associated 53-like n=1 Tax=Brachionus plicatilis TaxID=10195 RepID=A0A3M7PHX5_BRAPC
NENLVQKSNRIKFERETFNASHKLDVNDKIKFDFFTDIDRKAKIKQIDRTVEEIMNQRnFLLFE-RRKKLKDLLNFEDKMYEQELLSS
>UniRef100_A0A3S1BT70 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Elysia chlorotica TaxID=188477 RepID=A0A3S1BT70_ELYCH
PDWLTQKNREFDDRVKDLEARVKEQKKHDLRTDFETHSQKRIFAGSVKTKVKTLQQANEFNLECRRQKLKALLASEEACLIREMEES
>UniRef100_A0A401SLC7 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Chiloscyllium punctatum TaxID=137246 RepID=A0A401SLC7_CHIPU
ANADLVKELEQDLRAETYANFVRVHKEYETQNRVILEQEQMQLKGNIRYRVQRAMEFYENGIEQRRIKLRDLLEAEEKDYMNQLSLL
>UniRef100_A0A6P7SPR8 Cilia- and flagella-associated protein 53-like n=1 Tax=Octopus vulgaris TaxID=6645 RepID=A0A6P7SPR8_OCTVU
YTMYQESVLRYRQYAEGKKEDTFIQTLATNHISWEEITEKKMVDSAVKRKVRCKFEEEEKQLEERQLRLKKLLSDEENALLNEIESV
>UniRef100_A0A6P7X5Q7 Cilia- and flagella-associated protein 53 n=1 Tax=Microcaecilia unicolor TaxID=1415580 RepID=A0A6P7X5Q7_9AMPH
GEAVLYHERKRELQINSYKTVVKQNKWKDVVSQWELLTDHKVIHNTTQRKVHEAMQQYRMGTDERRQRLRELLEAEEKELIKEMESM
>UniRef100_A0A7I8W0C7 DgyrCDS10111 n=1 Tax=Dimorphilus gyrociliatus TaxID=2664684 RepID=A0A7I8W0C7_9ANNE
PDKIVREARRQQERLEEAALIAKQNRLADIKSDWETTTNRKIMLNNVKSKMAGMKAARTAELENRRERLRQLLGREEDSYINEMVNK
>UniRef100_A0A7J7J2W4 CCDC11 n=1 Tax=Bugula neritina TaxID=10212 RepID=A0A7J7J2W4_BUGNE
LDNIILDARRKQEELDNAEKLAKEQAFIDLKNTWDRETERKLMASSIKRKVKSMMNANQTEVEMRRDRLREMLRAEEEQYLMEMEDK
>UniRef100_A0A7K4XMJ2 CFA53 protein (Fragment) n=1 Tax=Regulus satrapa TaxID=13245 RepID=A0A7K4XMJ2_REGSA
REEAILAERVREEAQRDHERVLRVFWHHRNACEWHKGGEDKWMQRAAERKVQAALQQYLQEVDVRRQRLRDFLEAEESRHFAEVEaLD
>UniRef100_A0A7M5X2J6 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Clytia hemisphaerica TaxID=252671 RepID=A0A7M5X2J6_9CNID
AEHLILERRRIEDLREKSIADTKNNKQAFFMSQWEKTTDRQIQKNRIKREVEKNLSYANMILERRRDKLREKLLQEEEQYIHELEMK
>UniRef100_A0A812BCN5 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Sepia pharaonis TaxID=158019 RepID=A0A812BCN5_SEPPH
-QKNALKCMQREQWLRQAEEDAVQEKFARERLKWEDVTDQKIFINNVKTEINKHLKNEQFDLEARQEQLRQLLSQEEEEYFNLLEQN
>UniRef100_A0A8C5LLQ3 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Leptobrachium leishanense TaxID=445787 RepID=A0A8C5LLQ3_9ANUR
IDYLILENRRQNEVRDQLLAFTKETKFELMKNNWERNTDYKIMHNMVQRKVYKTMEEYRMHIEERRDRLKDLLEKEELEHIKEMESM
>UniRef100_A0A8S3ZU34 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Candidula unifasciata TaxID=100452 RepID=A0A8S3ZU34_9EUPU
ADWFIRKNREVGERLHEMEIQVQEQKLRDIRTDFETSGERRILITNVKSHVKTLMDANECTLECRREKLQNMLANEEACYMKEIEEQ
>UniRef100_A0A8X7XCJ6 CFA53 protein (Fragment) n=1 Tax=Polypterus senegalus TaxID=55291 RepID=A0A8X7XCJ6_POLSE
GLPGEERRRRQEDARKDMLAFVQYQDTWDVKNKWEQLSQKRITHGAVQRRVNEGLHLYHSGIEDRRLRLRNLLEEEEKLFIAEMECK
>UniRef100_B3RSC4 Trichohyalin-plectin-homology domain-containing protein n=2 Tax=Trichoplax TaxID=10227 RepID=B3RSC4_TRIAD
SDHIVMASQRRENIRNDALEILATTKKTDMKANWENSTQKKIMRNHINRKMDEASQERRLALEERRDHLRELLYCEEQQYLQELASL
>UniRef100_E4XTB3 Trichohyalin-plectin-homology domain-containing protein n=2 Tax=Oikopleura dioica TaxID=34765 RepID=E4XTB3_OIKDI
YVIQERQRTALQNQRQDAMNQKMTQLTFDLKNEWEKKTDNAIRRRNIQNRVNAKLFEHELALEERKNRLSEILTEEESNFENELQhhLN
>UniRef100_G3W8G4 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Sarcophilus harrisii TaxID=9305 RepID=G3W8G4_SARHA
AEKHLRKLRHDTYKKEAIENAMKENEKFHLGIEWDMHIDRISMNKNVQRQVEDAMQGVLLNTEERRNRLRELLEAEENQYLAEIQMK
>UniRef100_T2M7R9 Coiled-coil domain-containing protein 11 n=1 Tax=Hydra vulgaris TaxID=6087 RepID=T2M7R9_HYDVU
AEHLTLERRKIEELRNQSISEAKYDKLKKLKAVWEMKTDQLLEKSCVMRNIDKHFQEEQKALEIRKEKLKLMLEAEEKKYLLELD--
>UniRef100_UPI000719BAA4 cilia- and flagella-associated protein 53-like n=1 Tax=Priapulus caudatus TaxID=37621 RepID=UPI000719BAA4
-----------------------------MKTNWETRTNKRIECNSIKRKVSERMIESDISLEERRERLRLQLQQDEENYLHEIERQ
>UniRef100_UPI0014036ABD cilia- and flagella-associated protein 53 isoform X1 n=2 Tax=Amblyraja radiata TaxID=386614 RepID=UPI0014036ABD
SQSKMVKETEQDLKCDTYKQFVEDFEVCRRRNILAVEDERKELLCRIKNNLKKAMVFYVAHIEERRERLRELLEAEEKEYMNQLNLL
>UniRef100_UPI00140371AF cilia- and flagella-associated protein 53-like n=1 Tax=Petromyzon marinus TaxID=7757 RepID=UPI00140371AF
AVSAQASERWRQQAREDALALVQADKLARVKGEWEQRSEQRATRSTVDRHLYTAMQGLSLSLQDRRERLTKLLEEEERGYLEELQRT
>UniRef100_UPI001F03E421 LOW QUALITY PROTEIN: cilia- and flagella-associated protein 53-like n=1 Tax=Xenia sp. Carnegie-2017 TaxID=2897299 RepID=UPI001F03E421
PEHLILERRRNEGYVEKTMKEKKDLKQCDLKSQWLKTTNKRIERNTLRRRVQQEMLRGgKFALEDRRSMLRQMLLTEQQDYIREMENM
>UniRef100_UPI00223CF81D 182 kDa tankyrase-1-binding protein isoform X1 n=2 Tax=Pristis pectinata TaxID=685728 RepID=UPI00223CF81D
TQSKMMREADLDSVCQEYRKFVKDFEECKLKNVLELEEEHKRLLCSVRHKLKKAMEFYKDDIEERRERLRELLEAEEKDYVNQLNLL
>UniRef100_V9KSN7 Coiled-coil domain-containing 11 n=1 Tax=Callorhinchus milii TaxID=7868 RepID=V9KSN7_CALMI
MQAKIEKQKKLEIALEEALAFEKYQRDGLTRNKLERIEEQKRMRFKINQNFKGIMLEYKASIDDRRDRLRELLETEEEALLKEFVGL
>UniRef100_A0A2I2UDC9 Methyl-CpG binding domain protein 1 n=1 Tax=Felis catus TaxID=9685 RepID=A0A2I2UDC9_FELCA
--KKDRMRDKTRLLKEKKEKERQDFVTEKLDQQFRPIL-------------------------------------------------
>UniRef100_A0A2Y9IQZ7 Methyl-CpG-binding domain protein 1 isoform X12 n=1 Tax=Enhydra lutris kenyoni TaxID=391180 RepID=A0A2Y9IQZ7_ENHLU
--GPAGLRRWDTAGDAAPHRKCTASDLASYRGRLRAPLPKW----------------------------------------------
>UniRef100_A0A8C2SH94 Methyl-CpG-binding domain protein 1 n=1 Tax=Capra hircus TaxID=9925 RepID=A0A8C2SH94_CAPHI
--MDWHHLVWKLQILLYSSRDKVLADHKVLPTPDAKALKGFLIPCYCSVCFSLPSTAISSLVKMYLRA-------------------
>UniRef100_A0A8D2G727 Methyl-CpG binding domain protein 1 n=1 Tax=Theropithecus gelada TaxID=9565 RepID=A0A8D2G727_THEGE
--CKFLDSLVRARIKDAVQGFIINIEERRNK--------------------------------------------------------
>UniRef100_F7FBN3 Methyl-CpG binding domain protein 1 n=1 Tax=Macaca mulatta TaxID=9544 RepID=F7FBN3_MACMU
--SIKAQRQAAQLLKEEEARLVESNNAQIKHENEQDKLKKQKAKQETRTILQKALQDRIEHIQQDYREEQDLNMKLVQRALQDLQEE
>UniRef100_UPI000FFC802E methyl-CpG-binding domain protein 1 isoform X1 n=2 Tax=Tupaia chinensis TaxID=246437 RepID=UPI000FFC802E
--VPDITYKSERSVLSHKIKYCGHVPEKEIEEFWVF---------------------------------------------------
>UniRef100_UPI001FF628A8 methyl-CpG-binding domain protein 1 isoform X1 n=1 Tax=Prionailurus viverrinus TaxID=61388 RepID=UPI001FF628A8
--GPAGLHSRETRGGGRPHPEGLENVQPAIWHHTAGG--------------------------------------------------
>UniRef100_A0A8C0GZL0 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Chelonoidis abingdonii TaxID=106734 RepID=A0A8C0GZL0_CHEAB
------------------------VIKMSNCRAVILLGVDHDHECQPQGRLSKLLLKYFLPF-----RLRALLEAEEKSYFTEME--
>UniRef100_A0A8D2Q3N3 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Varanus komodoensis TaxID=61221 RepID=A0A8D2Q3N3_VARKO
--------------------------MAFSADKCKVLHLGHRNGSHKYRLGDKRLKSSTCKRD--LEVLRDLLEAEEKAYFAEME--
>UniRef100_UPI002094FAC6 cilia- and flagella-associated protein 53 isoform X2 n=1 Tax=Caretta caretta TaxID=8467 RepID=UPI002094FAC6
------------------------RSTWQELRIEETGRLEVYLWDKMRAKTDSCGRPLW-----RHLRLRALLEVEEKSYFTEME--
>UniRef100_A0A3B3Q6L7 Cilia and flagella associated protein 53 n=1 Tax=Paramormyrops kingsleyae TaxID=1676925 RepID=A0A3B3Q6L7_9TELE
PDFLILDRRRQETALGEVSDFTRYQKACEVRNQWEISTERRMVHRTTERRVQDAVRERMVCLEDRRDRLRSLLETEEKELLSEMEV-
>UniRef100_A0A3P8P8Y2 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Astatotilapia calliptera TaxID=8154 RepID=A0A3P8P8Y2_ASTCA
------KNASRVEERKTSEEVHGCSEGGHAE-GWCDRGGCRVDGGIQYLQSVLAVTSFSPN---RVLRLAELLEVEEQQFLQEMEE-
>UniRef100_A0A3Q3WCV1 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Mola mola TaxID=94237 RepID=A0A3Q3WCV1_MOLML
HSVAVVSQRHLTLQQACLSRKFDYSDL-----IWVP---------VCSRFVCLAHDVSACHpVPVCLSRLRALLEAEEQQLLQEME--
>UniRef100_A0A3S2PGI2 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Oryzias javanicus TaxID=123683 RepID=A0A3S2PGI2_ORYJA
EEPKDAAREPRGTPPSAGAPFSVPLEGCGFRLRLRRDVHRR---------ARAALEEHEAELHERRRRLQQLLQVEELHLLQEVEE-
>UniRef100_A0A553RBQ8 Trichohyalin-plectin-homology domain-containing protein (Fragment) n=1 Tax=Danionella translucida TaxID=623744 RepID=A0A553RBQ8_9TELE
IDELFLRRRKQEVTRGEVLQFSKDQHSCDLRMQWEKSTQRRIVSATINRRLQEALEQYQMSTNERRERLRVMLESEEKGLFKEMET-
>UniRef100_A0A6A5FGE4 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Perca fluviatilis TaxID=8168 RepID=A0A6A5FGE4_PERFL
--CGPSDPGPTEAGRCQRRDPGLHQEPAELQHEDLVAADFRptLSKDPVQRQVGAALTQQEVHVDQRRDRLRVLLEEEEQQLLQEMEE-
>UniRef100_A0A8C1F026 Cilia and flagella associated protein 53 n=1 Tax=Cyprinus carpio TaxID=7962 RepID=A0A8C1F026_CYPCA
VDE----RRKQEAIRNEVLEFTKNQSSCDVRMRWERNTQRRMVSATIK------------------------IISLGEGALQGDGG-
>UniRef100_A0A8C6UZE1 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Neogobius melanostomus TaxID=47308 RepID=A0A8C6UZE1_9GOBI
--------------KDLLLLLQQKGVPQSINSCCMNTCACP----TFQNHVSFCVHFTVAC-----YLLRVLLETEEQQYFNEIEK-
>UniRef100_A0A8T0AZZ9 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Silurus meridionalis TaxID=175797 RepID=A0A8T0AZZ9_SILME
MDYFNMERRKQDTARNTLLDFTKDQSACNIRMRWEKNTEKKMVSATIKQRVHKAMEQYEMSIDERRKRLHNLLESEERELLRELQT-
>UniRef100_UPI00072EC189 cilia- and flagella-associated protein 53-like n=1 Tax=Poecilia latipinna TaxID=48699 RepID=UPI00072EC189
LQRLVDRNQKLKEIRDEVLEFTNEYRDCIMKLWWLQRCERRYVRGAVVRGVEAELEEHEANISQKRDRLRRLLVAEEQQLLQQLEE-
>UniRef100_UPI0009B49096 LOW QUALITY PROTEIN: cilia- and flagella-associated protein 53-like n=1 Tax=Monopterus albus TaxID=43700 RepID=UPI0009B49096
ADHLTLERQKQDATRDEVLEFTRYQQTCDIKNSWLQSSERHFLRRADQRHVLAAVRQHESGVEERKDRfpLCLFLFQGGRRLstlphlrtllsylvqfsaalylfsssegnrvlftAPHLFN-
>UniRef100_UPI00106E54B1 cilia- and flagella-associated protein 53 isoform X2 n=1 Tax=Perca flavescens TaxID=8167 RepID=UPI00106E54B1
LHQEPAELQHEDLVAADFRPTLPPRIRPETSRSCSDPAGGPRGPEEGQAACAAGGGGAAAPAGDGGEDGDSGGETGEDERTSQSSE-
>UniRef100_UPI0011133E05 LOW QUALITY PROTEIN: cilia- and flagella-associated protein 53-like n=1 Tax=Echeneis naucrates TaxID=173247 RepID=UPI0011133E05
-----VNSTEHRLCLSRSXELTSCQRTSDVRNRWLKASDQHFRRGAIERRVRAAETEREAALDQRRQRLRKLLEDEEQQLLRELED-
>UniRef100_UPI0011452B14 cilia- and flagella-associated protein 53 n=1 Tax=Takifugu rubripes TaxID=31033 RepID=UPI0011452B14
ADYQMQERLRQEAARTKVQEFAKEQQNCGIKNSWLKTTESHFQRQDIERQIQKCLKKQRSQAEERRTRLHALLQEEEEQLLWEMEE-
>UniRef100_UPI00145B225C cilia- and flagella-associated protein 53 n=1 Tax=Periophthalmus magnuspinnatus TaxID=409849 RepID=UPI00145B225C
PDYLTLERRKQEAERENFAEFTKYQRSWELKNSWIKSSDRNYVRSATERHVKAAIDQFELGTEERRERLRIMLETEEQQFLKEMEE-
>UniRef100_UPI00147177F9 cilia- and flagella-associated protein 53 n=1 Tax=Thalassophryne amazonica TaxID=390379 RepID=UPI00147177F9
PQHFILARQKQDALREEALEFTKYQKTCDMETSWLKNSERHIQEGRVRRQVRDAVKSYETSIDEKRDRLRVMLETEDQQFLKLLEV-
>UniRef100_UPI00189F3259 cilia- and flagella-associated protein 53 n=1 Tax=Sebastes umbrosus TaxID=72105 RepID=UPI00189F3259
VDQLIQDRQRQRAARDQVQDFTKSQTTWDTKTSWLQRADQRFLRGETQRRVRVALNQQKVHMDERRDRLRVLLEEEQQQLLQEMDE-
>UniRef100_UPI001C047290 cilia- and flagella-associated protein 53 n=1 Tax=Melanotaenia boesemani TaxID=1250792 RepID=UPI001C047290
RGRAAIRDHVQESHRDQVQEFYRDLQSCDVTASWLQSSEQRFLRGDVQRRVRAAMDRHESEAQEPRTRLRQLLEDEEQQFLQELEE-
>UniRef100_UPI001CD81B94 cilia- and flagella-associated protein 53 isoform X1 n=1 Tax=Solea senegalensis TaxID=28829 RepID=UPI001CD81B94
-----LQRPKPAALREELVEVIKKERACDHMISWLKRTDRGYLRGAINKHVKDAVMEHESSVEQRRNRLRELLLQEEQQLLQELEG-
>UniRef100_UPI001CDB4FF5 cilia- and flagella-associated protein 53 n=1 Tax=Gambusia affinis TaxID=33528 RepID=UPI001CDB4FF5
VQHLVHRNQKLKEIRDDVLEFTKEYRDCSLKQWWVQRCERRYVRGAVARGLEAELEQHEANISQKRDRLRQLLVEEEQQLLQQLEE-
>UniRef100_UPI00232A388F cilia- and flagella-associated protein 53 n=1 Tax=Pleuronectes platessa TaxID=8262 RepID=UPI00232A388F
HDEILMERREKDFARDQLLKFSRNQKSCDITSSWLETSERHILNGAVNREVQAALKLYETDVEHRRHRLQAVLAEEEQQLLQELED-
>UniRef100_UPI000A1C19BE oncostatin-M-specific receptor subunit beta-like n=1 Tax=Boleophthalmus pectinirostris TaxID=150288 RepID=UPI000A1C19BE
PDYLTLERKKQETERENFAEFTKYQRSWDIKNSWIKSSDRNYVRNTTERQVKAAINQYELSIEERRARLRIMLETEEQQLLKETEE-
>UniRef100_A0A6G0I2R7 Cilia-and flagella-associated protein 53 n=1 Tax=Larimichthys crocea TaxID=215358 RepID=A0A6G0I2R7_LARCR
VDQLIVDRQKQDAARGRAVQLKTEQQSCDVKNSWLKKSDGRFLRRTIERRVQAAVRQNQVQIQDRRDRLRVLLQMEEQQLLQEMEEK
>UniRef100_UPI00155F03F3 cilia- and flagella-associated protein 53 n=1 Tax=Etheostoma cragini TaxID=417921 RepID=UPI00155F03F3
ADHLILDRQKQDVAREEVQSFARHQQSSDRKTTWLQTSERRFLRGTIERQVRAALDQQEVHLDQRRDRLRVLLQAEEQQLLQEMEEK
>UniRef100_A0A8T2N5Q3 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Albula glossodonta TaxID=121402 RepID=A0A8T2N5Q3_9TELE
---QLDNRRKKEEAHKNLLHFTQYQNQCDLKSEWEKNTGRRIILGTIQRRVQDALDQQRVAIDDRRERLRDLLEAEERQLLAEMAA-
>UniRef100_A0A0L0HK32 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Spizellomyces punctatus (strain DAOM BR117) TaxID=645134 RepID=A0A0L0HK32_SPIPD
SDFLIANRRREEETRTRMREQIQYYEKTALQSHFEESTNAAIMRNRIMRRFEELKSQENSKLEQRRERLRQLLAHDDERYQKELAS-
>UniRef100_A0A139A5V3 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Gonapodya prolifera (strain JEL478) TaxID=1344416 RepID=A0A139A5V3_GONPJ
PDYLIRARQREDQQRNLLLERTQYYLKAEQIAQFEHKTTENIKRNRLRRRFGELKAAADEEVDRRREKLRDLLASDVDEWRSELAL-
>UniRef100_A0A1Y2H7R8 Tumor suppressor, Mitostatin-domain-containing protein n=1 Tax=Catenaria anguillulae PL171 TaxID=765915 RepID=A0A1Y2H7R8_9FUNG
-----MSRQRAESIHEANLAQKTYYERTALIARFAEEAELTIRRRAVPRRVAAWRQADALVTEERKDRLRALMDEDTALWRAELLA-
>UniRef100_A0A4P9XAQ5 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Caulochytrium protostelioides TaxID=1555241 RepID=A0A4P9XAQ5_9FUNG
-DVFAAMRRKADLERERMATHTQYLQRTDAASRFENGVDRVVIQRHVRHALAEHRDAAAAALAARQAKLRALLAADAAREQAALQA-
>UniRef100_A0A7S0NB27 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Phaeocystis antarctica TaxID=33657 RepID=A0A7S0NB27_9EUKA
ADYLILKRRQQEEHKVFYERVCKSNFLAGANAEWEIKTSGNIAAMKTQKRFDAIRRADSAALDARRQRLADMLGREQQAQEQGLAL-
>UniRef100_A0A8J5XKZ4 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Diacronema lutheri TaxID=2081491 RepID=A0A8J5XKZ4_DIALT
ADFVLMQRRKQETARATMAASVRADYAVGAYADWEVRTDAKLKQRAVAQRYESIRAQDKAALIERRRRLAQMLLAEEAAFQQQIDA-
>UniRef100_A0A672HQC7 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Salarias fasciatus TaxID=181472 RepID=A0A672HQC7_SALFA
----------------------RSQKDCEIHNSWEQSTQQRFLRREVDRRVQGAVSADQALLDNKRFRLRKMLEAEERQYLQELEAK
>UniRef100_A0A1W4WYQ2 Cilia- and flagella-associated protein 53 n=1 Tax=Agrilus planipennis TaxID=224129 RepID=A0A1W4WYQ2_AGRPL
----------------------ASNAKDKFEQKFIKHSDQRLFKNEIEKRVKERLEIYEKTIEERRTRLRELLGEEECAHYRE----
>UniRef100_A0A1Y1MUJ7 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Photinus pyralis TaxID=7054 RepID=A0A1Y1MUJ7_PHOPY
----------------------LQRSKDSFSMKFEKHSQKRRFHSEIEKRLNAKMRDYEDAIDKRREKLRELYAEEERDYIRE----
>UniRef100_A0A482VWP6 Coiled-coil domain-containing protein 11-like n=1 Tax=Asbolus verrucosus TaxID=1661398 RepID=A0A482VWP6_9CUCU
----------------------KRLMKDRAVARYDRHTERKVLQRHIQERFKDKVEAYDGSIEKRREKLRDLLCKEEQEFIEE----
>UniRef100_A0A7J7B663 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Lamprigera yunnana TaxID=370605 RepID=A0A7J7B663_9COLE
----------------------KEYADNRFYVGCNKHIDIQRFTSEVHKRVAARMNEYEATINVRREKLRILLTKEEQEHSHE----
>UniRef100_A0A7J7BNA4 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Abscondita terminalis TaxID=2069292 RepID=A0A7J7BNA4_9COLE
----------------------TGLDKELFLLWHEQHAEHRQFLTKLDKQLQIQMTEYEASIDKRREKLKELLTGEEREFTKE----
>UniRef100_UPI00083BE774 cilia- and flagella-associated protein 53-like n=1 Tax=Nicrophorus vespilloides TaxID=110193 RepID=UPI00083BE774
----------------------KLNYVEMSNIQAQERAEKNRFKNHIKERLNQKLEHYEANVERRREALRVLLGDEERELIRE----
>UniRef100_UPI0008745578 cilia- and flagella-associated protein 53-like n=1 Tax=Anoplophora glabripennis TaxID=217634 RepID=UPI0008745578
----------------------EMYSSQANIIRNDINAEKAFLKRLIQMKVEKKIEDYENAVERRRERLRDLLCKEERQFYYE----
>UniRef100_UPI000C20549A trichohyalin-like n=1 Tax=Onthophagus taurus TaxID=166361 RepID=UPI000C20549A
----------------------KKVAKENYLVTWETHTGSSRFKRNLNLRLQEKMNAYDDEIERKRERMRKLMAEDERDFYYE----
>UniRef100_UPI001E2794DB trichoplein keratin filament-binding protein-like n=1 Tax=Harmonia axyridis TaxID=115357 RepID=UPI001E2794DB
----------------------SQAMADKIFIQYFNHYNKKDLQRDIKLRMEAKLKAADDALELRRQKLLEMLSIEEKQFYYE----
>UniRef100_UPI0021667CB5 cilia- and flagella-associated protein 53-like n=1 Tax=Anthonomus grandis grandis TaxID=2921223 RepID=UPI0021667CB5
----------------------KKYLQDAITTKYENHAVKKRLQRSIQDRVDEKLKAYEETVEARRRRLQELLCKEERAFYYQ----
>UniRef100_UPI0021B03EE3 cilia- and flagella-associated protein 53-like n=1 Tax=Diabrotica virgifera virgifera TaxID=50390 RepID=UPI0021B03EE3
----------------------KLYQKNYMFMMYDTHVEKKRIQRKIQEKVEQKVQAYEESVNKRREKLQKMLCAEERQFYHE----
>UniRef100_A0A817HMF2 Trichohyalin-plectin-homology domain-containing protein n=2 Tax=Rotaria sp. Silwood2 TaxID=2762512 RepID=A0A817HMF2_9BILA
---LVAQNRELEAIRETREKQNREAKTELNKIQFDELSSTKAFHAQVRREVERRINHADHQLEDRRERpkxxxxLRALLAADDAQYLAEAES-
>UniRef100_A0A0G4EN75 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Vitrella brassicaformis (strain CCMP3155) TaxID=1169540 RepID=A0A0G4EN75_VITBC
SDYLISRRRQQEDRHLSLCKDVHSLNTAQQKAEWEQKSDGVIATKRIESLSKAKQATHRQNLVDRQQRLINLLESERLAYEAELR--
>UniRef100_A0A0G4I884 Uncharacterized protein n=1 Tax=Chromera velia CCMP2878 TaxID=1169474 RepID=A0A0G4I884_9ALVE
ADYLISRRRQQEDFQKGLETIVKGNAHAQTKAEWEEKATAACVNANIKLKTDALRAQYKERLALRQQRLCDLLSAEQAQYEQEIR--
>UniRef100_A0A8J2FHX9 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Amoebophrya sp. A25 TaxID=1410381 RepID=A0A8J2FHX9_9DINO
PDRVILKRQKDESRYEALVDSNLDQNRVEAKAHWENKTTATIRTKRFESKVKSLLAEQRdAATHERRKKLSALLYKEKDMYEAELA--
>UniRef100_A0A8K0K9V2 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Ladona fulva TaxID=123851 RepID=A0A8K0K9V2_LADFU
--RFLIEKRKREEWSRKNMEAQKDRLMQTVKNQFEEITERKCVKRTIENKVDCGMKAASHDLEKRRERLRKLLMEEDLHFKKEAC--
>UniRef100_A0A0L0DRB0 Flagellar associated protein n=1 Tax=Thecamonas trahens ATCC 50062 TaxID=461836 RepID=A0A0L0DRB0_THETB
PSRLIEQRRRREDAIRAHQEKVNYLNEAQLKAEFEQRTNKRIRTNNVRRTYDSLKEADDEALATRKAKLRQMYAQEEQVLREEIAL-
>UniRef100_A0A2R5GLV9 Trichoplein keratin filament-binding protein n=1 Tax=Hondaea fermentalgiana TaxID=2315210 RepID=A0A2R5GLV9_9STRA
ADYTIIKRREGEQRRAHLEAGIRQVDRFTDLAKWEQKSEAAMARQRVRAGMQQRLAAHEQNLDRRRRALADLLQREREQLEEEFRN-
>UniRef100_A0A7S0K9X4 Trichohyalin-plectin-homology domain-containing protein n=2 Tax=Cafeteria roenbergensis TaxID=33653 RepID=A0A7S0K9X4_CAFRO
EPLNIRRRKAAEAQFERANAMIADRRTVSKMVEFEHRSDAAVRRRLVKERVAQTKEQMEADLRRRRAKLARLLEAERHEYEREIEA-
>UniRef100_A0A7S1CCG8 Trichohyalin-plectin-homology domain-containing protein (Fragment) n=1 Tax=Bicosoecida sp. CB-2014 TaxID=1486930 RepID=A0A7S1CCG8_9STRA
PDYAIMKRRAEEDRIAGHVAAARDKNKAMVMAHFEQRTGARIERRAADARVRKAKASLDADLDRRRRKLAQLLEDEQEQYEREVEA-
>UniRef100_A0A812YNA7 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Symbiodinium sp. KB8 TaxID=230985 RepID=A0A812YNA7_9DINO
DPPNIRARKAAEARIEGIQRIQTEMHKTMVAAKFEESSNRMLKQRMASNKLEEAKAALEADLLRRRKKLAQLLSAEQVAFQKEIEA-
>UniRef100_A0A195DFA8 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Trachymyrmex cornetzi TaxID=471704 RepID=A0A195DFA8_9HYME
------------------------YNQLLKTLEFKKETDRKIRNKNLRQRVQQDMSAYEEDLQARREKLRNLVSNEEANLTREIM--
>UniRef100_A0A6P8LVL1 Trichoplein keratin filament-binding protein-like n=1 Tax=Bombus bifarius TaxID=103933 RepID=A0A6P8LVL1_9HYME
------------------------YEHLTKILEFENQTNSKIKKKSVWQRVQQapikllsrtddspGLASFEDGVNARREKLRELLLKEEMGLIHEVI--
>UniRef100_E2B2J0 Reticulocyte-binding protein 2-like protein a n=1 Tax=Harpegnathos saltator TaxID=610380 RepID=E2B2J0_HARSA
------------------------YERALKTAEFEKETDRKIRSRSLHQQAQQGVSAYEERLRLRRARLRDLVRCEDSGQARQLA--
>UniRef100_UPI000771DD33 cilia- and flagella-associated protein 53-like n=1 Tax=Cephus cinctus TaxID=211228 RepID=UPI000771DD33
------------------------LEQVISRVAFEQRTEKRIIREKIRQGVEQGMAAYDQDIEKRREKLRKLIILEETALTNEIV--
>UniRef100_UPI000C71628A cilia- and flagella-associated protein 53 n=1 Tax=Orussus abietinus TaxID=222816 RepID=UPI000C71628A
------------------------LKKFLAQMAMERRTDKKIITETIRQRVDQglddasrffvqGMAAYEESVQIRREKLRRMLLVEEASLAKELL--
>UniRef100_UPI0014433AB7 trichohyalin-like n=1 Tax=Megalopta genalis TaxID=115081 RepID=UPI0014433AB7
------------------------YENLTKTMDFERQTDRKIGKKKLWNHVQQellirkvsdqrlidrrfnfggisyqkvplkwlqlqqvpcssinglpmfsinfadtamasaGLAAYQDSVNARRQKLREVLLREQMSLTREVV--
>UniRef100_UPI001C9D1FD4 trichohyalin-like n=1 Tax=Venturia canescens TaxID=32260 RepID=UPI001C9D1FD4
------------------------LISFLRTNDFVEKTDKRIRKEKIRSLIDEGLTEYEQSINARREKLRALLLAEEKSWIREVV--
>UniRef100_UPI0021F6856C calponin homology domain-containing protein DDB_G0272472-like n=1 Tax=Leptopilina boulardi TaxID=63433 RepID=UPI0021F6856C
------------------------EKHLHDTINFIQRTKKKCEKNVFDAKIKLGIDAYEEDLNRRREKLRKLMLNEEEILTKEII--
>UniRef100_UPI000B3DEE53 vicilin-like seed storage protein At2g18540 n=2 Tax=Numida meleagris TaxID=8996 RepID=UPI000B3DEE53
---FAFARRRREQELAELSAAVKRENQARGFSEWQRRNEAKWVRGDARRKADSALRELRAATESRRERLRAVLEAEVEA--------
>UniRef100_A0A1B6H8Z5 Trichohyalin-plectin-homology domain-containing protein (Fragment) n=2 Tax=Homalodisca liturata TaxID=320908 RepID=A0A1B6H8Z5_9HEMI
-----------DEAAKDNEQMMKRNQREIIKSKFHIKTDKKGLEAKIRSRVNERLQAVEEVLDHKRERLRELLLAEEKEYIREY---
>UniRef100_A0A1R2BY53 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Stentor coeruleus TaxID=5963 RepID=A0A1R2BY53_9CILI
ADFMIQQRRAKEGELQGLHGYLQDDHKLRHKAHWEAKSDNIVTQANFTKRFQEIRAVHSQQLDARRKKLSELFRAEEEMYKREY---
>UniRef100_J9JAG2 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Oxytricha trifallax TaxID=1172189 RepID=J9JAG2_9SPIT
SDAAIYARRDYEEKVSRLANDLRGDKNLLHKAQWEHKTNNIIQKNIVRNRLVDLKKREESNLQERRQRLKLLMDTEDRMYEQEF---
>UniRef100_UPI000C6CD6FC cilia- and flagella-associated protein 53-like n=1 Tax=Centruroides sculpturatus TaxID=218467 RepID=UPI000C6CD6FC
-----------EDNRYEIEQYVSENKKKQFYGEWYIQAEKKLTANIAQHKIKDALKNRNDWLEERRDRLRQLYEDEKNKYFQEIEQ-
>UniRef100_UPI000497C3E1 cilia- and flagella-associated protein 53-like n=1 Tax=Cynoglossus semilaevis TaxID=244447 RepID=UPI000497C3E1
---------RQESIIEDKTNAIKSARASDAKVSWMQNTQRHFLREEINRRMRAAQEEHENDVEQRRSRLKQLLKQEEEHTLQEMER-
>UniRef100_UPI002110CDA7 cilia- and flagella-associated protein 53 isoform X1 n=1 Tax=Syngnathus scovelli TaxID=161590 RepID=UPI002110CDA7
----MLLRQRQEEERQRASECAREREACRVNNRWLLTSEARNAGHSVRRDVDDVMMQHRCAVHQRQQRLRQLLEDEERQLVLSA---
>UniRef100_UPI00223DF25E cilia- and flagella-associated protein 53 n=1 Tax=Hippocampus zosterae TaxID=109293 RepID=UPI00223DF25E
----MLLRQKQDQLRERATEGTRENEACRVNNCWLLSSDARYVGHTVRRDVDDVMMQHRFSVHQRQQRLRELLDEEERQLVLAA---
>UniRef100_A0A7S3J871 Uncharacterized protein (Fragment) n=1 Tax=Euplotes harpa TaxID=151035 RepID=A0A7S3J871_9SPIT
-DRAIHARREEEARLSVLNNALRENANMRRTAEWEQKTDGLVVKRIVQTRISQKKGEKERALDERRRRLALKLQQEEAVYQQELQ--
>UniRef100_A0A7S4PCN1 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Guillardia theta TaxID=55529 RepID=A0A7S4PCN1_GUITH
PDFMILNRRKAEDQRRVFDEKCKSDASVERFAHWEHKTAGKIERNTVTRKVETMKQDMKEELNERRSKLAALLAEEDARYTAELSS-
>UniRef100_A0A1B6DK41 DNA topoisomerase I DNA binding eukaryotic-type domain-containing protein (Fragment) n=3 Tax=Clastoptera arizonana TaxID=38151 RepID=A0A1B6DK41_9HEMI
-----------EEIAKGDLQALKLDRREKVLTEFDKTTYKKSIVAKIQEKVDQALKSVEVDLECRRSRLRNMLLAEENMYLNEY---
>UniRef100_A0A8S0Z001 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Arctia plantaginis TaxID=874455 RepID=A0A8S0Z001_ARCPL
--EFVKKLRASEKELKRLEKEALKKAEDKYKITFFSRCQRK---------------------------LKDLYAIEEKENVR-----
>UniRef100_UPI001C204C2C axoneme-associated protein mst101(2)-like n=1 Tax=Aricia agestis TaxID=91739 RepID=UPI001C204C2C
--ACVLR-RATALYVLRARYSDPDRLSAQLAVYWFediaaVRASRRPVVRRSERELAAATRSSLAAGVAGRLK--ELYACEEQENIK-----
>UniRef100_A0A7J6L1B4 Coiled-coil domain containing 11 n=1 Tax=Perkinsus chesapeaki TaxID=330153 RepID=A0A7J6L1B4_PERCH
PDRLILQRQKQERLYEDRISAAIENSSLQKLAEWENKGGQVHRQQRVEARIADLRKRRQLFLDHRRAKLSQLLNKEEEMYAKELEE-
>UniRef100_C5L8M5 Uncharacterized protein n=1 Tax=Perkinsus marinus (strain ATCC 50983 / TXsc) TaxID=423536 RepID=C5L8M5_PERM5
PDRLILQRQKQDRLYEERISAAVENSSLQKLAEWENKGGQLHRRQRVHACIEELRKRRQLFLHHRRAKLSELLKSEEAMYARELEE-
>UniRef100_A0A8J8NSE1 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Halteria grandinella TaxID=5974 RepID=A0A8J8NSE1_HALGN
--AAIYARRDAEERVARLATQIKGDMNLRHKAHWEQKSENLIKRTIIRSRLTDLKRREESNLEERRNRLKQLLDAEDQVYEQE----
>UniRef100_A0A1Y2EML7 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Neocallimastix californiae TaxID=1754190 RepID=A0A1Y2EML7_9FUNG
VDYIIIQRRKEEAEHELMVKQNNYYKMMDKKADFERATVDANMRYNLYKNYTQLKNIQKEQFEQRQQRLAALFEKDRIEWAKLIEE-
>UniRef100_UPI0005CED314 arginine and glutamate-rich protein 1 n=1 Tax=Ceratosolen solmsi marchali TaxID=326594 RepID=UPI0005CED314
---------------------------------DERRHKRKLISINVQKIVDQGMEAYEEDLEVRRDNLRRLLLIEEADLTREL---
>UniRef100_UPI0006C9E2DF trichohyalin-like n=1 Tax=Copidosoma floridanum TaxID=29053 RepID=UPI0006C9E2DF
---------------------------------QEKREQWKAIEVEIKRRVQLGMEAYEQDLEERRDQLREMLVREEAELTREL---
>UniRef100_UPI000C719D54 trichohyalin n=1 Tax=Trichogramma pretiosum TaxID=7493 RepID=UPI000C719D54
---------------------------------VNRLREKKVIARNIKERVKLGLEAYEEDIEERRDRLRELLLREEAEQTREL---
>UniRef100_A0A061R2E2 Flagellar associated protein n=1 Tax=Tetraselmis sp. GSL018 TaxID=582737 RepID=A0A061R2E2_9CHLO
PDHRILKIRAYEDKLARFEEAFKEQGKLRCIADWEQRTGNRIKQRMINSRFEQLRAEREKSLDARRERLAHKLFDEEKALQQELLD-
>UniRef100_A0A0D2KVA4 Flagellar associated protein n=1 Tax=Monoraphidium neglectum TaxID=145388 RepID=A0A0D2KVA4_9CHLO
PDARITKIREYEDRMQQMQQAAKEESKLGSGAAWQHKTDARIQRNAEQACFEALRAARAGEIELRRERLAQKLAEEEQALKEELAA-
>UniRef100_A0A150H3J2 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Gonium pectorale TaxID=33097 RepID=A0A150H3J2_GONPE
PDARIQKMRELEDRLATLQQDRKAEQKMVAVADFETRTTKKIVSSLVQQRYDALKARQEADLNARRKRLAEKLEYEDVALREELLA-
>UniRef100_A0A1Y1HMU5 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Klebsormidium nitens TaxID=105231 RepID=A0A1Y1HMU5_KLENI
PDSRILKMREYEDRHRALTEATVAQQQIMATAEWEMTTDRRIKAQVIQGRFQHLKDREEQRLEERRERLAEMLRAEEVQFQQELRS-
>UniRef100_A0A250X9F8 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Chlamydomonas eustigma TaxID=1157962 RepID=A0A250X9F8_9CHLO
ALAAQSKLREYEARLQEMN--INESKRVSSAIQWQMSSDAKLRSNIVKQRFEELRQRREVDLDARRARLASKLMREDAQLKQELID-
>UniRef100_A0A5B8MVV4 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Chloropicon primus TaxID=1764295 RepID=A0A5B8MVV4_9CHLO
-----------------MQDIVKYNEKRGELALWEQKTDANIKKNEVRKRYEAIMARAEHELEDRRLRLRSLLQLEQASLQQELES-
>UniRef100_A0A7R9YTX3 Trichohyalin-plectin-homology domain-containing protein n=2 Tax=Chlamydomonas euryale TaxID=1486919 RepID=A0A7R9YTX3_9CHLO
NLAQEQRYREYEARRAKLG--IKEELFFGAVVDWNVRSETKAKSTLVRQRFEQLKARRAEALDERRRELANKLLREEAQLKAELLS-
>UniRef100_A0A7S0KEV0 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Micromonas pusilla TaxID=38833 RepID=A0A7S0KEV0_MICPS
ADFRIQKMRAADEKSNQMQAYVKSWKTKEFGAVWEHNSNNMIARNQFKQRFEALKAQAEANVDARRRKLAAKLHAEELALQNELVA-
>UniRef100_A0A7S0N3H2 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Pyramimonas obovata TaxID=1411642 RepID=A0A7S0N3H2_9CHLO
PDARILKMRAKEEQTQGYCDHVKHSANVHALASWENRTDAVIKRNIIMQRYEQLNAQAEADLDMRRQRLAAKLSEEEIDLQIELKR-
>UniRef100_A0A7S0V1K5 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Polytomella parva TaxID=51329 RepID=A0A7S0V1K5_9CHLO
PDARIIKMREIEEKINRMKVANEADKFTGEKALWEERTVERMRRNVIQQRLDALKHRREMDVNVRRQRLAELLSAEDARLKQELID-
>UniRef100_A0A8S1IN65 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Ostreobium quekettii TaxID=121088 RepID=A0A8S1IN65_9CHLO
PDARILKMRDKEDRLARIQRSVQEDRVLDAVTTWEDKSNQKIQANQAQERFVRLKADRSAALDARRRRLASKLLEEERALEAELVR-
>UniRef100_A0A8S4GM35 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Pedinophyceae sp. YPF-701 TaxID=765719 RepID=A0A8S4GM35_9CHLO
PDASILKRRDYEAKLEKLARDEKEMKQKERMAHWEVRTGQRQQRTQHAMAAEEMQWQREEVLERRRQALKAKFEREEAQYKQEMWS-
>UniRef100_A0A7S2CP91 Uncharacterized protein (Fragment) n=1 Tax=Alexandrium andersonii TaxID=327968 RepID=A0A7S2CP91_9DINO
ADRAIVQRQKQEFIHETLVAGEVDAFAVKQKGVWENKTAAVIRNNRVKSKAAALEAQHKASLQQRRLKLAQKLSAEMKAYEREMVE-
>UniRef100_A0A812MGS3 Uncharacterized protein n=1 Tax=Symbiodinium sp. CCMP2592 TaxID=631055 RepID=A0A812MGS3_9DINO
PDRAILKRQEQEFHYETRVANQLDQFKVEQKGHWENRMMSVIRGNRVKGKVAALQAQQQEQLQERRLRLANKLSDEMKAWQREMVE-
>UniRef100_A0A8S3X1P3 (apollo) hypothetical protein n=1 Tax=Parnassius apollo TaxID=110799 RepID=A0A8S3X1P3_PARAO
--KFVRKLRAEEEEQRKGAVNKAKEIKDNQINDFFLRCDRRSLINDVAHRVDLCMASYQEDLNQKRDKLKDLFAREEEENIRKL---
>UniRef100_A0A6A5C755 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Naegleria fowleri TaxID=5763 RepID=A0A6A5C755_NAEFO
-NHSINQRRKQEQHWETFNAIKQTDAKHRFAAEWESKTTTKIQKGQLQKRLDELRKEKEKDLERRRNKLAEKLALEDEQFKQELESM
>UniRef100_A0A1J4K4L5 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Tritrichomonas foetus TaxID=1144522 RepID=A0A1J4K4L5_9EUKA
---MLLDRRAREETNRFYHEAEAADMRIRQRADFETRTFSRFQAGELKRRAKQRSEEAEAQINERRNRLALLFREEEAKYAEEIQ--
>UniRef100_A0A1J4L5V6 Coiled-coil domain-containing protein 11-like n=1 Tax=Tritrichomonas foetus TaxID=1144522 RepID=A0A1J4L5V6_9EUKA
-----MERRARDEALQVHNETAKGDFISRQKAEFETRSFHNYQSREIKRRAKERQRQAEELVNQRRQRLAALFREEEERLSVDIC--
>UniRef100_A2G2G6 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Trichomonas vaginalis (strain ATCC PRA-98 / G3) TaxID=412133 RepID=A2G2G6_TRIV3
---RINDEIERNDRLRFYNEAARDDKIARIRQNFIDDSTRHYNAKETARRVIARREEAEKDLERRRDLLAELLQRDEEMYIDEIQ--
>UniRef100_R1C9Y4 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Emiliania huxleyi TaxID=2903 RepID=R1C9Y4_EMIHU
PDYLILKRREQEDARRVYEDHGREQSKVGATTAFEVRTDAALGARRLNERYNRLRQQDAAALEGRRRRLAELLAAEQAEQAA-----
>UniRef100_A0A0N0U6H9 Lysine-specific histone demethylase 1A n=2 Tax=Apocrita TaxID=7400 RepID=A0A0N0U6H9_9HYME
----------------------KEYEHLTKLLEFENQTNSRITRKSARQRVQQGLASFEESVNARREKLRDLLLKEEMGLIHEVI--
>UniRef100_UPI0005AC62B1 trichohyalin-like n=1 Tax=Fopius arisanus TaxID=64838 RepID=UPI0005AC62B1
------------------------LQNFINMREFEERTDKIIALNRVREFIEQGMMAHEEDINIRREKLRHMLEKEDSELMREVV--
>UniRef100_UPI0006D50622 trichohyalin-like n=1 Tax=Microplitis demolitor TaxID=69319 RepID=UPI0006D50622
------------------------LEYSRNSLTLKERTDKTIRRNQIRDCIQKNTSANEEDINIRRAKLRNMISSEEALLSRELV--
>UniRef100_UPI001D01E74C golgin subfamily A member 6-like protein 22 n=1 Tax=Cotesia glomerata TaxID=32391 RepID=UPI001D01E74C
------------------------HANGASNLLLLGESSTAAKID-----INTQSLSNVNDISTRQERLRSVILSEEALLAKEIL--
>UniRef100_A0A024GB91 Uncharacterized protein n=1 Tax=Albugo candida TaxID=65357 RepID=A0A024GB91_9STRA
-DALIIKRRQRENNVAKLVHAISDSNNQCHRANWEQNVQSKDRAAKIHQTYSKLKNQQESQLHARRIRLAELYNRELEEW-------
>UniRef100_A0A662XCE0 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Nothophytophthora sp. Chile5 TaxID=2483409 RepID=A0A662XCE0_9STRA
-ESLILKRRQREDHLASYSSSVQGFAKVNSRAEWEYSLHQKGESKQVQRTVLQLKNQHESQLHSRRLKydihgirrrLAELYNSEMDMW-------
>UniRef100_A0A6L2Q5L9 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Coptotermes formosanus TaxID=36987 RepID=A0A6L2Q5L9_COPFO
--------RKMEELRRRNLTMARETNELVGRHEFEEVTDRKGLVNKMRRGMQAELEVVRRDLEVRRNKLRCVLLQEEEACTREYL--
>UniRef100_A0A7R9JA52 (California timema) hypothetical protein n=1 Tax=Timema californicum TaxID=61474 RepID=A0A7R9JA52_TIMCA
--------RDQRHLSEENEKNESLRKELLmksVKNKFEATTELKSIFGGVRNQVQLGMRAVRNELDQRRDKLRQLLLEEEDAWTRKFI--
>UniRef100_A0A7S0GFB1 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Proboscia inermis TaxID=420281 RepID=A0A7S0GFB1_9STRA
-----------------------DNFKVEFNAQWETKTTEKIKKREIIERVRESEETKQKRTEERKNAVSTMLHNEMEDWKGKLaF--
>UniRef100_A0A7S1XRQ7 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Phaeomonas parva TaxID=124430 RepID=A0A7S1XRQ7_9STRA
---QMALNRRKNEATEERIAHIGLSREALLKADWENKTQSRIEQRQEALLRARDEETAAERLRARRARLKGLYDAEYGGWITEMQ--
>UniRef100_A0A7S3YAB2 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Heterosigma akashiwo TaxID=2829 RepID=A0A7S3YAB2_HETAK
---MFMKRREQEAQRENFTAATQQVAHLQRLAKWEARTDSVINNRLQKERLRELTEANEQELLGRRRRLADLYNSEMEQWTREVL--
>UniRef100_A0A812P941 CFAP53 protein n=1 Tax=Symbiodinium microadriaticum TaxID=2951 RepID=A0A812P941_SYMMI
---VIEARKKANAEYDIMDSVISENKRRMQIANFEISTQKKIETRMKMDRIKDMRRQNEISIHHRRRLVADMFNDEMDQWQAEVL--
>UniRef100_A0A835YTH0 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Tribonema minus TaxID=303371 RepID=A0A835YTH0_9STRA
---RFEKTRAQERQLENSIASINKTRAALQYATWENKTHDAIAARQGRDRMTRLTEADKAALEGRRRRLAAQRQQEMAEWEHEVL--
>UniRef100_B8BRA0 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Thalassiosira pseudonana TaxID=35128 RepID=B8BRA0_THAPS
------RRRDRERILHETESFLHQHNNTERLLDWENRTQQQIQQREESNLAQQFQKQDEDELNKRQNELQSLYNREMSEWKDTLqR--
>UniRef100_D8LQ98 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Ectocarpus siliculosus TaxID=2880 RepID=D8LQ98_ECTSI
---QFARKREKERRWEQSVESIAATDKVIAFANWENKTAGAIASRAGADRVRSLEGADADALLARRRRVADLYNLEMEQWEHEIL--
>UniRef100_G0QU44 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Ichthyophthirius multifiliis TaxID=5932 RepID=G0QU44_ICHMU
-IRAIYQRRNYEEHIDKLQTKLNQEFYEKQFAVWENRGQKVNQAKYMKQRLQQLREESQRQLNQRKQKLALLLAGEHEQHKQRIKD-
>UniRef100_A0A0A1WN30 Cingulin-like protein 1 n=1 Tax=Zeugodacus cucurbitae TaxID=28588 RepID=A0A0A1WN30_ZEUCU
---------------------------DIFMLKFMNNSERKSVYRQIKDLVKKAHNVSKKELEQRRKRLHLQLEHDAHVYQEEFAI-
>UniRef100_A0A0A1X6B8 Reticulocyte-binding protein 2 homolog a n=1 Tax=Zeugodacus cucurbitae TaxID=28588 RepID=A0A0A1X6B8_ZEUCU
---------------------------HFAVCYFLKHSDLRSLSTQIKDLVTTAKDVMEKELIKKRERLRRLLEAENKIYEREFAH-
>UniRef100_UPI00177ACBBD eukaryotic translation initiation factor 3 subunit A-like n=1 Tax=Rhagoletis pomonella TaxID=28610 RepID=UPI00177ACBBD
---------------------------DVARHFFIERTDRKSLYIQLKKLVQTAQNVAAKELDQRRQMMRRMLEHEDQIYEEEFAN-
>UniRef100_A0A176WRW5 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Marchantia polymorpha subsp. ruderalis TaxID=1480154 RepID=A0A176WRW5_MARPO
---RIYKFRLYEDSLKERLQGVKEYQHIMRNAEFAHSFDAKRKFKETQAIVQTMQAHSEKSTITRKQKLAALLDGEESFLIDELK--
>UniRef100_A0A8T2VE95 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Ceratopteris richardii TaxID=49495 RepID=A0A8T2VE95_CERRI
---RIIKHRHYEDDLRDRLISVHNYEGLMRRAEFEKANEPKISYRTLSERLDAIRTERDRVISNRRNRVKKLLEEESNAVEEEMK--
>UniRef100_A0A9D4UK39 Uncharacterized protein n=1 Tax=Adiantum capillus-veneris TaxID=13818 RepID=A0A9D4UK39_ADICA
---VIYKARQHEKALQERLQFVQEYKGLMRYAQFEEGNGPRASHRCLAERLHALRHQREQELLQRRSRLSAILSAEDASLKHDIT--
>UniRef100_D8S1I0 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Selaginella moellendorffii TaxID=88036 RepID=D8S1I0_SELML
---RIYKQRQYEEARQARVDHVNEYEHLMRCAEFEQSNEPKLRFRAKMESEKSVMALKARQLAEKRQRLGDLLREEAEALHCELH--
>UniRef100_A0DPT0 Chromosome undetermined scaffold_59, whole genome shotgun sequence n=1 Tax=Paramecium tetraurelia TaxID=5888 RepID=A0DPT0_PARTE
SEQLIYQRRQQEQYVGKLNTKLRQEHYEKTFAAWENKGKDIANWQYTKNRLQQIRSEAEANKNQRREKLAFLLNAEHEQYQQEIKA-
>UniRef100_A0A2K1K081 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Physcomitrium patens TaxID=3218 RepID=A0A2K1K081_PHYPA
-EDRIYKMRMYENKIADNIQAVKSYNQLMRAAEFGEQHIKKREEREIESREEAIRQCREQNLEIRRAKLSALLEGEDQLLNDELKT-
>UniRef100_A0A388KXP6 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Chara braunii TaxID=69332 RepID=A0A388KXP6_CHABU
-EDIVFRERREEDVKLHRGYVMEEYRNAHLYADWEVKTDKVIKDGMILRKVEEMKRQREEMVEVRRSKLTERLLQDDREVLHELKS-
>UniRef100_A0A7S1LPH1 Trichohyalin-plectin-homology domain-containing protein (Fragment) n=1 Tax=Neobodo designis TaxID=312471 RepID=A0A7S1LPH1_NEODS
-TWQIELRQRQEDHVAKYNSVAQDHQRARMRSQWEQATDKKIGTTQMVRAMDAVQARHDEVLMARRKRLAELLKAERDEH-------
>UniRef100_A0A8T2QX57 Uncharacterized protein n=1 Tax=Ceratopteris richardii TaxID=49495 RepID=A0A8T2QX57_CERRI
--DRVFKQRRYEAARSSKLEEIREYEKLMERAAFDESCNDLLSRRNTELQVMQNKVLYLQSLAMRRSKLKNLLQAEEDQLHREIE--
>UniRef100_A0A8X6LBU8 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Trichonephila clavata TaxID=2740835 RepID=A0A8X6LBU8_TRICU
----------QQDVFQQIKDYAESHEKTLFRNRWECAADKKSLYSRVQWEMDKITSKMDQDLNRRRNRLTDLLKNEEDMLLKDS---
>UniRef100_B4I3Q0 GM10698 n=1 Tax=Drosophila sechellia TaxID=7238 RepID=B4I3Q0_DROSE
--------------------------RGADHFNFITRTDRKSLHTQIGLLVTKAKEVTAAELHERSRRLKNMLDEEDKRYEEEFSN-
>UniRef100_A0A0V0QHX5 Uncharacterized protein n=1 Tax=Pseudocohnilembus persalinus TaxID=266149 RepID=A0A0V0QHX5_PSEPJ
-MEHIKRSIQKNEQYRQNEAYANKLSSISRVTNWHESKVKYDNNNKKkienELIKQEVKCSQRELFQARNIRLKQLYEQEAEQWEQQLAE-
>UniRef100_A0A1R2BR12 Uncharacterized protein n=1 Tax=Stentor coeruleus TaxID=5963 RepID=A0A1R2BR12_9CILI
-DWSIQTRVRQDIKYSDAEAYARKMQDIAKTSTWHERQQKFEVARDNiraeDRSNFELQLANRELKERRRCRLRELLQSEAFQYEQELAK-
>UniRef100_A0A7S3KUS2 Flagellar FliJ protein n=1 Tax=Euplotes crassus TaxID=5936 RepID=A0A7S3KUS2_EUPCR
-GFNITQRVKEDERLREFNEYSKKMQAIGRTTDWHETQDKYSVMKANkaneKKIEAELEQANEDLKVLRNHRLKELYEKEMQQYQDELAD-
>UniRef100_A0A7S4FDT7 Uncharacterized protein n=1 Tax=Eutreptiella gymnastica TaxID=73025 RepID=A0A7S4FDT7_9EUGL
-PSNVRGYLKEQVGRENYQAYTSTVDATrNRNLPWEDCKGKMVPRKAMQEIHQEGQYGMLEAKELRRTRLRELYQGELEQWNRELNA-
>UniRef100_A0A8S1RJE8 Uncharacterized protein n=1 Tax=Paramecium sonneborni TaxID=65129 RepID=A0A8S1RJE8_9CILI
-MQQIKRNIKINQQYTDAERYDQNLKSISRNTWWHESKSKFDKVNELkfmnKVYSKEVENAYQELKKRRNCMLKDLYEREAREWEQELRT-
>UniRef100_A0A0M5J059 Guanylate cyclase n=2 Tax=Drosophila busckii TaxID=30019 RepID=A0A0M5J059_DROBS
--------------------TMQDNGRGEEHFQFIQRTDQKSLHTQIGLLVKKALQVTEEDLQDRHNRLKKQLEHEDTIYEQEFAT-
>UniRef100_A0A484BLK7 Guanylate cyclase n=1 Tax=Drosophila navojoa TaxID=7232 RepID=A0A484BLK7_DRONA
---------------------MQNHGRGEEHFQFMERTDRKSLHTQIGLLVAKAQQTAQEELQERSQRLKNMLDNEDKQYEQEFAS-
>UniRef100_A0A9C6U5W7 Trichohyalin-like n=1 Tax=Frankliniella occidentalis TaxID=133901 RepID=A0A9C6U5W7_FRAOC
---------------AVEQETSKELQRLALAMEFEESTRAKVMHGQAAALAHASERSVHLDLLRRRDQLRSLLAAEGIEMEGELS--
>UniRef100_UPI0021195368 cilia- and flagella-associated protein 53-like n=1 Tax=Schistocerca cancellata TaxID=274614 RepID=UPI0021195368
---------------AAIAGVQRKMQDDVLQLEFEERTARRQLMTEARAKVQSGLRAAEVALQQRRDRLRDMLQKEDSALTAECV--
>UniRef100_A0A7S3JZD5 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Aureoumbra lagunensis TaxID=44058 RepID=A0A7S3JZD5_9STRA
----MERRRAKEARIEETMKHNAMITKTRSLAVWENRTLETIERSNKERRIREDNSRRQAEVTERQIKLNELYKKEEKMWREQIE--
>UniRef100_A0A8J2SRN2 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Pelagomonas calceolata TaxID=35677 RepID=A0A8J2SRN2_9STRA
----IERRRAAQEVTDDLKRHNTDMWLSTERAKWEQKTHDKIVERGRRARIRKYDKEAEDELRRRRERLAKLYSEEMAQWRHEVA--
>UniRef100_A0A1I8GZ52 Flagellar FliJ protein n=1 Tax=Macrostomum lignano TaxID=282301 RepID=A0A1I8GZ52_9PLAT
----------ADEAVEKHQATLNEEWKVNMKSDWEARCQARHRVNAAKAVQKQLDGElkctKAVLIEVRKEALRQLLERERSAYAKELEA-
>UniRef100_A0A7J7JJH2 Uncharacterized protein n=1 Tax=Bugula neritina TaxID=10212 RepID=A0A7J7JJH2_BUGNE
----------EDEFIEAMEQQLKRETKINQRANWDDKCQLKTEYKRIKAGESIVRGEmhiaAKCLVEVRRAALKRLLEAEMAQYTEELNA-
>UniRef100_A0A913Y4P1 Uncharacterized protein n=1 Tax=Exaiptasia diaphana TaxID=2652724 RepID=A0A913Y4P1_EXADI
----------YDEWMSGRDAAVKNDIRVNLIADWAEKLEETSACRSVKRWHEETKDElaltNKELSAVRKAQLRKLLTEENMIFQQELKN-
>UniRef100_UPI001F045D83 uncharacterized protein LOC124459419 n=1 Tax=Xenia sp. Carnegie-2017 TaxID=2897299 RepID=UPI001F045D83
----------NYEIMNEKTNAVRSDIKTILLADWVEKLDETCFKKKAKRHAEEVKQElhhgNEELILVRRAQLQNLLMKEEKSYRDELEK-
>UniRef100_A0A7S0GZ72 Trichohyalin-plectin-homology domain-containing protein (Fragment) n=1 Tax=Amorphochlora amoebiformis TaxID=1561963 RepID=A0A7S0GZ72_9EUKA
--KAILASRRRNEQIETMTKRNNDIKAHQRYLDFEIKAQDIVRKTHLNRIADGLRQKEAENLDHRRKRLAELLGREEIIFQEEID--
>UniRef100_A0A418EX79 Ubiquitin-like domain-containing protein n=1 Tax=Aphanomyces astaci TaxID=112090 RepID=A0A418EX79_APHAT
-EQSIMKRRNREDSLSMYTGVVKGLSHMNARADWETKLHDKAGVRDTLNMLKTLKNQDESNLASRRLKLATLMNAEMDAWKQ-----
>UniRef100_A0A7R8UBZ0 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Hermetia illucens TaxID=343691 RepID=A0A7R8UBZ0_HERIL
----------------------KGDLKILQTYEFVKRTDERALRRKIQDLVDLAKQVRKEELAEKRERLRELLAKEESEFEQEY---
>UniRef100_A0A088SAE1 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Leishmania panamensis TaxID=5679 RepID=A0A088SAE1_9TRYP
--SFIEARQRRESFMEKFTAEQTAQNRQKHTVEWELRGNERHEQKEVLEYMDVIQAQHNDVLIARRRRLAELLARENALHTS-----
>UniRef100_A0A0S4IRE4 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Bodo saltans TaxID=75058 RepID=A0A0S4IRE4_BODSA
--AAIEARQRQEEVVRDYARVTAENGRQKLIADWEIKSGHTVSKKELYRHMDGVQAQHDDILIARRQRLTELLQQEKAEYDA-----
>UniRef100_G0TVB2 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Trypanosoma vivax (strain Y486) TaxID=1055687 RepID=G0TVB2_TRYVY
--NIIEARKYREEQQRMYDRARLEHNRMRLAANFEARGEVVGERKELMRHLDLVQAKNDDVLVARRQRLAALLLREKDEHEA-----
>UniRef100_W6KTX7 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Phytomonas sp. EM1 TaxID=479712 RepID=W6KTX7_9TRYP
--AVIEARQRREAFMREFEASQASELRQKLNVEWELKGNAKIYQKELFRVLDKVEARHNDTLVERRKRLADLLCREQAQYDH-----
>UniRef100_A0A0G4H680 Flagellar FliJ protein n=1 Tax=Vitrella brassicaformis (strain CCMP3155) TaxID=1169540 RepID=A0A0G4H680_VITBC
PDFTLVRRAAANEKQRDAEQYAQRLVKQNQTTKWFEAGVTnarRINRKRESKFEQEELRMANQELtLRRQTRLRQLYESEAQMYEAELE--
>UniRef100_A0A812IN34 Uncharacterized protein n=1 Tax=Symbiodinium sp. CCMP2456 TaxID=1519616 RepID=A0A812IN34_9DINO
PDFLIQKRIQKDNQFAVAADYASKMAAISQVTHWFEGKQKfdfAETEKRSSEFIKQEMNSCSEELkIRRRTRLRNLYEAEAgsQAFLLQFR--
>UniRef100_A0A813IEW5 Uncharacterized protein n=2 Tax=Polarella glacialis TaxID=89957 RepID=A0A813IEW5_POLGL
PDFIIQKTIQKDNQYAAAADYKKQMDLIGGVTAWFEGKQKydfNEVEKRNQSFIQQEMHSCMEELkIRRRTRLRQLYDQEARGWESELA--
>UniRef100_A0A0G4IQA2 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Plasmodiophora brassicae TaxID=37360 RepID=A0A0G4IQA2_PLABS
---VVERRRREEDVLEQYRASARSEFKLKTMAQWEQQTHASIQRNQITRIAEGIRDAHQERLERRRGALVALLAADDAVLKKELNA-
>UniRef100_F2USW8 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Salpingoeca rosetta (strain ATCC 50818 / BSB-021) TaxID=946362 RepID=F2USW8_SALR5
---GIDRRRALEARVQAAEQDITAHKETLYKERWVERTTRKAKAKAAEMRMQEILDEEQQELERRRAKLRQMLADEERHLLAEAA--

#Filter alignment to include the most divers 30 sequences only.
hhfilter -i "/home/kensch/Alignments/A3M files/ELLEn/ELLEn_query_msa.a3m" -o query.fil.a3m -diff 30

#Trim filtered alignment and remove all inserts with with respect to the first, master sequence in the MSA. Make file query.fil.fas.
/home/kensch/hh-suite/scripts/reformat.pl -r query.fil.a3m query.fil.fas

#Save filtered, trimmed ELLEn alignment
mv query.fil.fas "/home/kensch/Alignments/A3M files/ELLEn/ELLEn_filtered30_trimmed.fas"

#Show filtered, trimmed, and curated ELLEn alignment.
cat "/home/kensch/Alignments/A3M files/ELLEn/ELLEn_msa_filtered_trimmed_curated.a3m"
>Q_cfap53_nt_minim_1/1-87
AEHHLERIRRSHQKHNAILASIKSSERDRLKAEWDQHNDCKILDSLVRARIKDAVQGFIINIEERRNKLREL
LALEENEYFTEMQLK---
>UniRef100_A0A1A8BTT5/1-87 Coiled-coil domain containing 11 (Fragment) n=1 Tax=Nothobranchius kadleci TaxID=1051664 RepID=A0A1A8BTT5_9TELE
PNYQFLQERRREAVRGQLLDYKKDIGNCDVKTSLFESSKHHYVRKAVERRVGADRQQHQAQINQRRCRFKQT
LETEKEQLLQEMKDK---
>UniRef100_A0A3Q0D103/1-57 Cilia- and flagella-associated protein 53 n=1 Tax=Mesocricetus auratus TaxID=10036 RepID=A0A3Q0D103_MESAU
AEQGFKRILPDGSACILAVPS------------WSCLAPYGFLHFLCPGGV----------------HLGCL
VFLSPVHYWVDMP-----
>UniRef100_A0A670ZS24/1-74 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Pseudonaja textilis TaxID=8673 RepID=A0A670ZS24_PSETE
------MLATLSLGDFNSQNSPASKLESKLAGEFWELKSSRLKVANLDFKIKPNCISFLF-------RLRDL
LETEEKGFIAEMESQ---
>UniRef100_A0A3M7PHX5/1-87 Cilia-and flagella-associated 53-like n=1 Tax=Brachionus plicatilis TaxID=10195 RepID=A0A3M7PHX5_BRAPC
NENLVQKSNRIKFERETFNASHKLDVNDKIKFDFFTDIDRKAKIKQIDRTVEEIMNQRnFLLFE-RRKKLKD
LLNFEDKMYEQELLSS--
>UniRef100_A0A6P7SPR8/1-87 Cilia- and flagella-associated protein 53-like n=1 Tax=Octopus vulgaris TaxID=6645 RepID=A0A6P7SPR8_OCTVU
YTMYQESVLRYRQYAEGKKEDTFIQTLATNHISWEEITEKKMVDSAVKRKVRCKFEEEEKQLEERQLRLKKL
LSDEENALLNEIESV---
>UniRef100_A0A7K4XMJ2/1-88 CFA53 protein (Fragment) n=1 Tax=Regulus satrapa TaxID=13245 RepID=A0A7K4XMJ2_REGSA
REEAILAERVREEAQRDHERVLRVFWHHRNACEWHKGGEDKWMQRAAERKVQAALQQYLQEVDVRRQRLRDF
LEAEESRHFAEVEaLD--
>UniRef100_A0A8S3ZU34/1-87 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Candidula unifasciata TaxID=100452 RepID=A0A8S3ZU34_9EUPU
ADWFIRKNREVGERLHEMEIQVQEQKLRDIRTDFETSGERRILITNVKSHVKTLMDANECTLECRREKLQNM
LANEEACYMKEIEEQ---
>UniRef100_E4XTB3/1-89 Trichohyalin-plectin-homology domain-containing protein n=2 Tax=Oikopleura dioica TaxID=34765 RepID=E4XTB3_OIKDI
YVIQERQRTALQNQRQDAMNQKMTQLTFDLKNEWEKKTDNAIRRRNIQNRVNAKLFEHELALEERKNRLSEI
LTEEESNFENELQhhLN-
>UniRef100_V9KSN7/1-87 Coiled-coil domain-containing 11 n=1 Tax=Callorhinchus milii TaxID=7868 RepID=V9KSN7_CALMI
MQAKIEKQKKLEIALEEALAFEKYQRDGLTRNKLERIEEQKRMRFKINQNFKGIMLEYKASIDDRRDRLREL
LETEEEALLKEFVGL---
>UniRef100_A0A8C2SH94/1-66 Methyl-CpG-binding domain protein 1 n=1 Tax=Capra hircus TaxID=9925 RepID=A0A8C2SH94_CAPHI
--MDWHHLVWKLQILLYSSRDKVLADHKVLPTPDAKALKGFLIPCYCSVCFSLPSTAISSLVKMYLRA----
------------------
>UniRef100_F7FBN3/1-85 Methyl-CpG binding domain protein 1 n=1 Tax=Macaca mulatta TaxID=9544 RepID=F7FBN3_MACMU
--SIKAQRQAAQLLKEEEARLVESNNAQIKHENEQDKLKKQKAKQETRTILQKALQDRIEHIQQDYREEQDL
NMKLVQRALQDLQEE---
>UniRef100_A0A3Q3WCV1/1-72 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Mola mola TaxID=94237 RepID=A0A3Q3WCV1_MOLML
HSVAVVSQRHLTLQQACLSRKFDYSDL-----IWVP---------VCSRFVCLAHDVSACHpVPVCLSRLRA
LLEAEEQQLLQEME----
>UniRef100_UPI00106E54B1/1-86 cilia- and flagella-associated protein 53 isoform X2 n=1 Tax=Perca flavescens TaxID=8167 RepID=UPI00106E54B1
LHQEPAELQHEDLVAADFRPTLPPRIRPETSRSCSDPAGGPRGPEEGQAACAAGGGGAAAPAGDGGEDGDSG
GETGEDERTSQSSE----
>UniRef100_UPI00155F03F3/1-87 cilia- and flagella-associated protein 53 n=1 Tax=Etheostoma cragini TaxID=417921 RepID=UPI00155F03F3
ADHLILDRQKQDVAREEVQSFARHQQSSDRKTTWLQTSERRFLRGTIERQVRAALDQQEVHLDQRRDRLRVL
LQAEEQQLLQEMEEK---
>UniRef100_A0A8J5XKZ4/1-86 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Diacronema lutheri TaxID=2081491 RepID=A0A8J5XKZ4_DIALT
ADFVLMQRRKQETARATMAASVRADYAVGAYADWEVRTDAKLKQRAVAQRYESIRAQDKAALIERRRRLAQM
LLAEEAAFQQQIDA----
>UniRef100_UPI000C20549A/1-61 trichohyalin-like n=1 Tax=Onthophagus taurus TaxID=166361 RepID=UPI000C20549A
----------------------KKVAKENYLVTWETHTGSSRFKRNLNLRLQEKMNAYDDEIERKRERMRKL
MAEDERDFYYE-------
>UniRef100_UPI001C204C2C/1-82 axoneme-associated protein mst101(2)-like n=1 Tax=Aricia agestis TaxID=91739 RepID=UPI001C204C2C
--ACVLR-RATALYVLRARYSDPDRLSAQLAVYWFediaaVRASRRPVVRRSERELAAATRSSLAAGVAGRL
K--ELYACEEQENIK---
>UniRef100_A0A1Y2EML7/1-86 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Neocallimastix californiae TaxID=1754190 RepID=A0A1Y2EML7_9FUNG
VDYIIIQRRKEEAEHELMVKQNNYYKMMDKKADFERATVDANMRYNLYKNYTQLKNIQKEQFEQRQQRLAAL
FEKDRIEWAKLIEE----
>UniRef100_UPI001D01E74C/1-56 golgin subfamily A member 6-like protein 22 n=1 Tax=Cotesia glomerata TaxID=32391 RepID=UPI001D01E74C
------------------------HANGASNLLLLGESSTAAKID-----INTQSLSNVNDISTRQERLRSV
ILSEEALLAKEIL-----
>UniRef100_A0A7S1XRQ7/1-82 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Phaeomonas parva TaxID=124430 RepID=A0A7S1XRQ7_9STRA
---QMALNRRKNEATEERIAHIGLSREALLKADWENKTQSRIEQRQEALLRARDEETAAERLRARRARLKGL
YDAEYGGWITEMQ-----
>UniRef100_A0A812P941/1-82 CFAP53 protein n=1 Tax=Symbiodinium microadriaticum TaxID=2951 RepID=A0A812P941_SYMMI
---VIEARKKANAEYDIMDSVISENKRRMQIANFEISTQKKIETRMKMDRIKDMRRQNEISIHHRRRLVADM
FNDEMDQWQAEVL-----
>UniRef100_D8LQ98/1-82 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Ectocarpus siliculosus TaxID=2880 RepID=D8LQ98_ECTSI
---QFARKREKERRWEQSVESIAATDKVIAFANWENKTAGAIASRAGADRVRSLEGADADALLARRRRVADL
YNLEMEQWEHEIL-----
>UniRef100_G0QU44/1-85 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Ichthyophthirius multifiliis TaxID=5932 RepID=G0QU44_ICHMU
-IRAIYQRRNYEEHIDKLQTKLNQEFYEKQFAVWENRGQKVNQAKYMKQRLQQLREESQRQLNQRKQKLALL
LAGEHEQHKQRIKD----
>UniRef100_A0A2K1K081/1-85 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Physcomitrium patens TaxID=3218 RepID=A0A2K1K081_PHYPA
-EDRIYKMRMYENKIADNIQAVKSYNQLMRAAEFGEQHIKKREEREIESREEAIRQCREQNLEIRRAKLSAL
LEGEDQLLNDELKT----
>UniRef100_A0A8X6LBU8/1-74 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Trichonephila clavata TaxID=2740835 RepID=A0A8X6LBU8_TRICU
----------QQDVFQQIKDYAESHEKTLFRNRWECAADKKSLYSRVQWEMDKITSKMDQDLNRRRNRLTDL
LKNEEDMLLKDS------
>UniRef100_A0A9C6U5W7/1-70 Trichohyalin-like n=1 Tax=Frankliniella occidentalis TaxID=133901 RepID=A0A9C6U5W7_FRAOC
---------------AVEQETSKELQRLALAMEFEESTRAKVMHGQAAALAHASERSVHLDLLRRRDQLRSL
LAAEGIEMEGELS-----
>UniRef100_A0A913Y4P1/1-80 Uncharacterized protein n=1 Tax=Exaiptasia diaphana TaxID=2652724 RepID=A0A913Y4P1_EXADI
----------YDEWMSGRDAAVKNDIRVNLIADWAEKLEETSACRSVKRWHEETKDElaltNKELSAVRKAQ
LRKLLTEENMIFQQELKN
>UniRef100_A0A088SAE1/1-80 Trichohyalin-plectin-homology domain-containing protein n=1 Tax=Leishmania panamensis TaxID=5679 RepID=A0A088SAE1_9TRYP
--SFIEARQRRESFMEKFTAEQTAQNRQKHTVEWELRGNERHEQKEVLEYMDVIQAQHNDVLIARRRRLAEL
LARENALHTS--------
>UniRef100_A0A813IEW5/1-89 Uncharacterized protein n=2 Tax=Polarella glacialis TaxID=89957 RepID=A0A813IEW5_POLGL
PDFIIQKTIQKDNQYAAAADYKKQMDLIGGVTAWFEGKQKydfNEVEKRNQSFIQQEMHSCMEELkIRRRTR
LRQLYDQEARGWESELA-





