#Show alignment of HHblits search human EFHC1 residue 222-330:
kensch@kbf-linux01:~$ cat "/home/kensch/Alignments/A3M files/DM10/EFHC1_Hs_222_330.a3m"
#A3M#
>Q_EFHC1_Hs_241
QVLRFYAIWDDTDSMYGECRTYIIHYYLMDDTVEIREVHERNDGRDPFPLLMNRQRVPKVLVENAKNFPQCVLEISDQEVLEWYTAKDFIVGKSLTILGRTFFIYDCDP
>UniRef100_UPI00077A4E64 EF-hand domain-containing protein 1-like n=1 Tax=Acropora digitifera TaxID=70779 RepID=UPI00077A4E64
-------------------LPDLI-HYNQNAYVKGRSIFDAVRTIDDVLEYTKRSEQSGVllflfSFFFAASFPSCVLELSNHEVKDWFTPRDFMVGQTLFILGRRFLLYDCDE
>UniRef100_A0A4E0QVS8 EF-hand domain-containing protein 1 (Fragment) n=1 Tax=Fasciola hepatica TaxID=6192 RepID=A0A4E0QVS8_FASHE
FTHDFL---ESEGIVINEPEPEPEDPYLAErarrESLPTSKTPSSfDKRRQQFELDRKVLRFYAVWDDRAEPFGECrkFSIQAKKEVKEYFQPSDFRIGHSINILGRKFLIYDCDN
>UniRef100_A0A8S1DP16 DM10 domain-containing protein n=3 Tax=Cloeon dipterum TaxID=197152 RepID=A0A8S1DP16_9INSE
QVLRFFAVWQdPMDPM-HEKRYFKVLFYLADGTMEIQPEYKVNDGHYKYPNLLARQLLPRG-----GLLPgKADLPSFRDMDC--YVAEDLQVGSEIEVLGRRLRLFDCDG
>UniRef100_UPI001C380A7F EF-hand domain-containing protein 1 n=1 Tax=Ixodes scapularis TaxID=6945 RepID=UPI001C380A7F
QVLRFFCVEDglLVSP--HSRKKLVLQYFLVDDTLDLREMHRPMETRDLAPILLGRQRVPRVQEH-KGLFY--QYEHERNQDD-YIGPEDLEPGKRLDIYGRSFLIYDCDD
>UniRef100_A0A224X9Q8 Putative ef-hand domain-containing protein (Fragment) n=1 Tax=Panstrongylus lignarius TaxID=156445 RepID=A0A224X9Q8_9HEMI
KVLRFQAIWDDDSVEFAEKTMYKINYFLEDDTIEINELRQPNSGKEGPTKIMTRRKIPKCVRKIQDSLPVY-LEMTEEDVNKYLEPLDFLVGKTVNIFYRRFLLIDCDE
>UniRef100_A0A7S3H0K4 DM10 domain-containing protein n=1 Tax=Spumella elongata TaxID=89044 RepID=A0A7S3H0K4_9STRA
KVLRFFGVWDCRGMLFGDEINVKVHYSLAENTIEVVPINGRNTGRDRLPKLLKKTSIMkplgsslssqDGFdfapggslsPSLGDRSPSGprsaspsrvntastqggnAMTLNTLAQQNKLTPNvpyhwtDLKVGLTIPVAAMTLLLVDADE
>UniRef100_A0A8S9XEN0 DM10 domain-containing protein n=1 Tax=Apolygus lucorum TaxID=248454 RepID=A0A8S9XEN0_APOLU
KVLRFTGIWDNRACEYGDLEEYHILYYPEDDTMEILKRSKRRETETT-APLLARIKVPKNWKKLRAIFPAESLENFYEHREEMYLPHDLLVGRTIDVFGRKIHLVDCDK
>UniRef100_UPI0006D4D3E0 EF-hand domain-containing protein 1-like n=1 Tax=Halyomorpha halys TaxID=286706 RepID=UPI0006D4D3E0
RILRFYAVWDRRTEENGILEKYKIYYYLADDTFDIYEDQDIGEMRIFdSKAILKKAKIPKAMNTLKKDLIPIVHEPSDDDVLQFYSPYDLIVGKTVFLMGRRFYLYDCDE
>UniRef100_A0A1Q9C6Z0 EF-hand domain-containing family member C2 n=1 Tax=Symbiodinium microadriaticum TaxID=2951 RepID=A0A1Q9C6Z0_SYMMI
KVLRFKA------APWRSAQ-------LSSLPQLRSSKMASGELSERVLVFMKRGPLRKSAF------------------------------------EARVVLWDCDD
>UniRef100_A0A6U0B444 DM10 domain-containing protein n=2 Tax=Ostreococcus mediterraneus TaxID=1486918 RepID=A0A6U0B444_9CHLO
QVLRFYCVWNDe--SQFGDRRKFVLQYFLIDDTVSISEAEPSGGGYGISSTMLNRLRLPIKDE-D--AgVHGPTQ-----DMFDYVTADDLRVGGFIRAYKRNFFIYAADE
>UniRef100_G0QQV2 Flagellar microtugule protofilament ribbon protein, putative n=1 Tax=Ichthyophthirius multifiliis TaxID=5932 RepID=G0QQV2_ICHMU
KVLSFNVLWND-NTLEGGINYYILNFYLSDDSIELKEIRRHNSGKDSFPMFLNKKKMPKIPIQT--YYPGMTL-----KKEEFYKPEDLLCGQTICLYSKDVLIFDCDE
>UniRef100_K8ERE1 DM10 domain-containing protein n=1 Tax=Bathycoccus prasinos TaxID=41875 RepID=K8ERE1_9CHLO
EVLRFYATWKGekdeREDATDDEKRmFCVHYFLADDTVEVIEKGGR-AllRRGKLPKISSTSEREKKTERE--QtiptpTPSAkplDFSV--CSigsSEriPHIVANEIVVGQTVNVYGRDMFIYGCDR
>UniRef100_A0A1J1IF72 CLUMA_CG012132, isoform A n=1 Tax=Clunio marinus TaxID=568069 RepID=A0A1J1IF72_9DIPT
MNLCFDCVLDETQRPGGELITFKMYYSLEDDTVAIRELPENQQGRDVSGMLLKRTKLPKDWRKTPIDFPAIIFNTTEAEIDEYYQPRDFIIGNTIFVFGRKFLLLDCDK
>UniRef100_A0A0H5RTV9 DM10 domain-containing protein (Fragment) n=1 Tax=Spongospora subterranea TaxID=70186 RepID=A0A0H5RTV9_9EUKA
---------------------FIVHFFRADGSLEVLEVRQANSGRDPFPALLKRVRLPRNVTFSN---QAQIGSDGVGDGEDFYNETDFRIGTTISVFGRNLLIIDMDT
>UniRef100_G0QSN9 DM10 domain-containing protein n=1 Tax=Ichthyophthirius multifiliis TaxID=5932 RepID=G0QSN9_ICHMU
KW------------------------------------------KRPFPINAQKIKLPK----------KFALNQPGqty--AEEFTKPQDITFGQFVDVFGRKFQVNGCDP
>UniRef100_UPI001AE90E9C EF-hand domain-containing protein 1-like n=1 Tax=Lepeophtheirus salmonis TaxID=72036 RepID=UPI001AE90E9C
EVLRFYAT-SRLPSYPlgqKENQKYIIYFYLSDHSIEIRENRNTLDSKEPFGKFLSRKCIQKHFDGHKfECMPSE----NRSSR-TFYSPEDFQIGEEIEILKKRFYIYDVDA
>UniRef100_A0A3B3RFI5 EF-hand domain (C-terminal) containing 2 n=1 Tax=Paramormyrops kingsleyae TaxID=1676925 RepID=A0A3B3RFI5_9TELE
KVLHFFCLWDDSESMFGDCRELTLHYFLSDDTMEIREIFCPNSGRDAVPKFLKRSKLPKVGhQPgrkranragnlsTGQETCQQGRKCFNragnvptgqetyqpgrkrvnragnvSTGQEtyFYKDCDLALGTVINVWGRKVLLCDCDS
>UniRef100_A0A3S2MFS2 EF-hand domain-containing family member C2 n=1 Tax=Oryzias javanicus TaxID=123683 RepID=A0A3S2MFS2_ORYJA
QVLRFYCFWNDQADPSAEPRELVLLYFLLDDTIQIHEVTSsAKGSKKTAAKFLQRRKLPKNPsAQveqLGGDTDSILLNVLTsdglgnrfmadrlqtgAVKQDFYKDWDLRIGGEVNVWGRRVIIADCDE
>UniRef100_A0A8K0KJZ9 DM10 domain-containing protein n=1 Tax=Ladona fulva TaxID=123851 RepID=A0A8K0KJZ9_LADFU
QVLRFWGYWDDRETPHGLLHHLRLHYYLADDTIEITEEGNKTEGLEMGPVFLRRTKLPKNFstVGlpgDDFGNPLTVLNVLGhsfkkghyiydslssgRndlgSRYEYVTDKDLYIGAALDAYGRNIVLTSCDP
>UniRef100_T1HFY7 EF-hand domain-containing protein (Fragment) n=1 Tax=Rhodnius prolixus TaxID=13249 RepID=T1HFY7_RHOPR
RKLTFHAYWDDRDNENGAVHLLLVIYYIVDETIEIKD-VT-D--KNKVVNVLKREKLKKDVqYRyegPGSTEPFTVLNALGkeneplrylidpldmgSDHTPIYTEKDLRIGAVLSALGRKLVMYDCDE
>UniRef100_UPI001D0596EC EF-hand domain-containing family member C2 n=1 Tax=Equus asinus TaxID=9793 RepID=UPI001D0596EC
QTQVTWIYWA---------------------------------------------------------------NVLFglestlasqrlySLTKECLKH---------------LGCCRYVP
>UniRef100_UPI0012D40E7E EF-hand domain-containing protein 1-like n=1 Tax=Contarinia nasturtii TaxID=265458 RepID=UPI0012D40E7E
IVLGFESIRIDEKKQLCDCVPYHISYYLEDGTISVKERKHRDESFDFCPYLIKRVRVPRYSKRLINSLIVAEEDSFseEKDERDYIQPSDFNVGKEVNLLGHRFLIRDCDA
>UniRef100_A0A5J4X111 Putative EF-hand domain-containing protein n=1 Tax=Streblomastix strix TaxID=222440 RepID=A0A5J4X111_9EUKA
KVLHFYADLDNKNESFGDMRQFAIQYYLSDDTTRVNEVYKNNSGYLEFPTFCRRQRIPKK----------VQGVIMDEPRTATIIVADLMIGRTVNIFNQPLLLYDYDE
>UniRef100_A0A5E4MJ69 DM10 domain-containing protein n=1 Tax=Cinara cedri TaxID=506608 RepID=A0A5E4MJ69_9HEMI
KVLRFYAAWHvnesESEYEPPNWRNFLIAYYLKDDEVEINELKYGknEV---PSPSFLKKMKLPMNLKNIPSILSYVTLNDNvKNECRRFYKPTDFIIGNTICVMGRRFILYDCDQ
>UniRef100_S9W654 DM10 domain-containing protein n=2 Tax=Strigomonas culicis TaxID=28005 RepID=S9W654_9TRYP
KVLRCDCTWDDSVSLHGYKHFLTLYYFLSDGSLALVEKETQNSGRDPFPRFFSRQKIARPTDP-NGKFdSSTLGsvTFKENKNTDYYSDKDIRIGKVLDLYGRKVKIHGYNQ
>UniRef100_A0A8T2P1E6 DM10 domain-containing protein n=1 Tax=Albula glossodonta TaxID=121402 RepID=A0A8T2P1E6_9TELE
KVLRFYALWEHADTIHTETRPVVVQFYLADDSLEIRETHEHNSGRDPYPVLLHRQKLFTQTP--HPDSPPCSVPIPPlptklTQILSYTQPppDSTPCLLTLPLSQAPHPVCSPCP
>UniRef100_A0A8T0HS23 DM10 domain-containing protein n=2 Tax=Ceratodon purpureus TaxID=3225 RepID=A0A8T0HS23_CERPU
KVLRFFCVWDDRAVPYGERRPYVLHYFLGDDTIEILELNERNSGRMHFPMLIRRQKILKETPHDL---LSQKKICGEKdfgPKESYYRDTDLHIGSYIRVFDRDLLLHDVDE
>UniRef100_A0A668AG82 EF-hand domain containing 2 n=1 Tax=Myripristis murdjan TaxID=586833 RepID=A0A668AG82_9TELE
KILRFYCFWDDTVNMFGVLHELILHYFLADDTIEINEVIYPNSGQDAVPKFLRRSRLPKHAptpkRQPGEITDRTVLNLFGsrGQgeryivdslkvwqiATLLNYFHSIQGKKVHACLTYV--------
>UniRef100_T1JFL8 DM10 domain-containing protein n=1 Tax=Strigamia maritima TaxID=126957 RepID=T1JFL8_STRMM
KALRFYCLRKEPEAGRG-VRPCVLMYFLSDRTIELCDSKSSSHptdfDCDSLPPFIERQKILKDHINENLG--------------GYYEPEDLIIGNTVYILGDKYLIYDCDQ
>UniRef100_A0A7S2XXW0 DM10 domain-containing protein (Fragment) n=1 Tax=Fibrocapsa japonica TaxID=94617 RepID=A0A7S2XXW0_9STRA
KVLRFFAMWDDTNRLYGDVLPFTLQYYVADDTMEVLQLHEANNGRHPFPKLLKRMKVPQPSDDGPEASMNRGMEFEGemDSKGKVYHWTDLAVGKSVTVFNRQLNLVDCDD
>UniRef100_A0A0G4GBL8 Calmodulin n=1 Tax=Vitrella brassicaformis (strain CCMP3155) TaxID=1169540 RepID=A0A0G4GBL8_VITBC
KVCRFYAMMDDVTTPIFERRPFVILYFLADNSVEIREMYPNNCGRDSFPIFFRRRKLPRDKMDFGS--PM---A-TMPKAEDYVKVTDFLVGKTMKLLKFEFHIFDADE
>UniRef100_A0A0G4HCV0 Calmodulin n=1 Tax=Chromera velia CCMP2878 TaxID=1169474 RepID=A0A0G4HCV0_9ALVE
KVCRFWAVLDDLSTPLFERRPFVILYFLGDDTIEVRENFPDNCGRDHMPIFFRRGKLPKGGAMCVG--PS---D-PVVSRGELVSPHDFAVGARISLLNQPFFIVDADA
>UniRef100_G0U750 DM10 domain-containing protein n=1 Tax=Trypanosoma vivax (strain Y486) TaxID=1055687 RepID=G0U750_TRYVY
KVLRFMGAWD--------NKMFRIQFYIADQTLSVMLEHVRNDGLDPNPVFIRRTKIPKCPTTR--TRDTETLNLPLGPPIQYVGEDDLRTGKSVNLFTRDFYIFDCDE
>UniRef100_A0A2P6U0Z3 EF-hand domain-containing 1 n=1 Tax=Chlorella sorokiniana TaxID=3076 RepID=A0A2P6U0Z3_CHLSO
EVLRFYLLWNVPAEQGGGHARFKLHFFVADSTAEIMEVPEAGTGCALFPTFLKRGPLPKVAKVGG-G-----LPGQGRlAPEDCFTPADLRVGSTVNILGRAFLIYDCDA
>UniRef100_A0A2P6VAL7 EF-hand domain-containing 1 n=1 Tax=Micractinium conductrix TaxID=554055 RepID=A0A2P6VAL7_9CHLO
EVLRFWIMWDDRAKQYGTRHLLKLHFFVADNTAEIMEIQGSNKGAG-FATFLKRGPLPKAAPAAA-GA---ALPGAARlTAEQCYAPTDMNIGATITILGRQFLIYDCDD
>UniRef100_W6KP80 DM10 domain-containing protein n=1 Tax=Phytomonas sp. EM1 TaxID=479712 RepID=W6KP80_9TRYP
--LSYLALWDDRGSISGDLHFCVIKLFLENFAIEVMEQRPENSNWSGGKVLISRQRTPKPGSDITkskfqeHTFGKL-------MKNGYLEPQDLMIGETYIMYGKPFFIYGCDQ
>UniRef100_A0A7M5VAV7 EF-hand domain-containing family member C2 n=1 Tax=Clytia hemisphaerica TaxID=252671 RepID=A0A7M5VAV7_9CNID
--MILIPCLVIHENVFCIISWLMILW-------RFVKLFNQNSGRDAVPLFLRRAKLPK-EST-EMHQPGkvtkrTVLNVfgptgqggryildslkTGAVHTEYYHDSDLVVGAIINVWGRKFTICGCDE
>UniRef100_UPI00017C2AF2 EF-hand domain-containing family member C2 n=1 Tax=Bos taurus TaxID=9913 RepID=UPI00017C2AF2
------------------------------------------------MTLLYKISGAGVGKC-TLTLDPvirgpEAVSVqgprcqvtal-------------GPTALTCMVFCEHLLLCDCND
>UniRef100_UPI00051C6841 EF-hand domain-containing family member C2-like n=1 Tax=Fulmarus glacialis TaxID=30455 RepID=UPI00051C6841
--------------------------------------------------------------------------------MASSREAPGRSG-MRNIPGEQGLLSPGRV
>UniRef100_UPI000522BF12 LOW QUALITY PROTEIN: EF-hand domain-containing family member C2 n=1 Tax=Haliaeetus albicilla TaxID=8969 RepID=UPI000522BF12
---------------------------------------------------------------------------kgqrRSHSVFKLKKNSDIXI---LSMYFKFILLLDKSD
>UniRef100_UPI00052364DE EF-hand domain-containing family member C2-like n=1 Tax=Nestor notabilis TaxID=176057 RepID=UPI00052364DE
---------------------------------------------------------------------------ITEGAHVIYKEKN------VGMVLPNPFLTDSGE
>UniRef100_UPI001C3F7C34 EF-hand domain-containing family member C2-like n=1 Tax=Callorhinchus milii TaxID=7868 RepID=UPI001C3F7C34
--------MHICPVNLSDFELPTLGNAWANSASD-----TTLAETSQTQHQLRVDPEFPHVPE-RLPHPGeitdhTILNVfgqmghagryildglkTGAVYQEMYKDSDLMIGAVINVWGRKVVICDCDE
>UniRef100_A0A7S1LI26 DM10 domain-containing protein n=1 Tax=Alexandrium catenella TaxID=2925 RepID=A0A7S1LI26_ALECA
RVLAFKCFWDDPT-RYGARLYYTMHFHLADDSVDIHENLAKNSGRDPFPVFFRRAQLRKNPHV--NPAPG-MIEPDP----VIYKPEDFMVGGFFEVHGRQIYIHDCDE
>UniRef100_U6H0G6 DM10 domain-containing protein n=1 Tax=Eimeria acervulina TaxID=5801 RepID=U6H0G6_EIMAC
KVLAFHCYWENQQ-NFGCRTYYKLHYFLSGQRGKLPKKLgelnlsDHQLSRSEFYTFIHTKLRRSDTLL--LRV---VFPGNP----ASYVAPPCACGPILTNVRFSL-------
>UniRef100_UPI001E1BAF51 EF-hand domain-containing family member C2 n=1 Tax=Daphnia magna TaxID=35525 RepID=UPI001E1BAF51
QILRFGCVWDrrEEEGVSVDERmkPYVLRYFLVDDTIQITDAEfesnqkrgLYSTNRAQEAVLLRRQRLPKEPRP-VMTSP------ADAADLTFYDPKDLILGNAISVHGRRFVFVETgDE
>UniRef100_UPI001EEAEF97 EF-hand domain-containing family member C2-like n=1 Tax=Daphnia pulicaria TaxID=35523 RepID=UPI001EEAEF97
QILRFGCVWDrrGEENVGLDERlkPYVMRYFLVDDTIQITDAEfesnqkrgLYSSNRAQEAVLLRRQRLPKEPRP-IMTSP------ADAADITFYDPQDLMLANVISVHGRRFVLVETgDD
>UniRef100_A0A5E4MEQ6 DM10 domain-containing protein n=1 Tax=Cinara cedri TaxID=506608 RepID=A0A5E4MEQ6_9HEMI
SILRFKGYSEEKNG--HNVRNLHILYYLVDDTIEIREMIEkTKSCKQECVVFLKRQKIPKNGPWcvfPGQNIKQNLLNsitnasdstyymldrHSLKPAVEHIHYTDLFIGATFSAKGNDVVLTECNE
>UniRef100_A0A8R2A5W5 DM10 domain-containing protein n=1 Tax=Acyrthosiphon pisum TaxID=7029 RepID=A0A8R2A5W5_ACYPI
LILRFRGYWDDRNQMDGDLHFYEVLYYLADDTMELVEEIMddTKVSGIRNKMIVKRQRLMKEGPWclqPGYNVRQDILNvmttnknsfyytmdsqLGIVQKVPYYNRTDLFIGQVLNVYGRSVILVSCDE
>UniRef100_A0A0G4IRV7 DM10 domain-containing protein n=1 Tax=Plasmodiophora brassicae TaxID=37360 RepID=A0A0G4IRV7_PLABS
TVLRFWARLEDQD-AApadESSQAFILHYFVEDDTVEIVRDKQCSKGasSDAARMLLRRQALPRRFTM--AGAASIGMDHS-ET-VGMYTAGDLRIGAVIEAYGRRLRLLRADR
>UniRef100_A0A8T2P1E6 DM10 domain-containing protein n=1 Tax=Albula glossodonta TaxID=121402 RepID=A0A8T2P1E6_9TELE
PCLLTLPLSQTPHPVCSPCPSARIHTLLT-------LHPAPQSDSTPY------------------PFPSCVLEVSPKEVQEYYSPRDFIVGEPVSIMGREFLLYGCDE
>UniRef100_A0A672IER3 EF-hand domain (C-terminal) containing 2 n=1 Tax=Salarias fasciatus TaxID=181472 RepID=A0A672IER3_SALFA
QVISIMPYFQEAVqEVQEGRnriRKCKIYFYLEDDTIQVVDPEYKNRGIPQ-GTLICRQRIPLPPPR----------------PGA--LLQHLPLQHQPP-GGAVLPHIHRDQ
>UniRef100_A0A6H5GAF4 DM10 domain-containing protein n=1 Tax=Nesidiocoris tenuis TaxID=355587 RepID=A0A6H5GAF4_9HEMI
TILKFDAFWLESAaFPEEGNrhfvHKCVVYFYLEDGTVKVVEPKIRNSGLPQGkytsl-SLVERRRQRIQYyrGDGS-------------TNDN-YDIIDFNIGKEVDIYGRKFTLVDCDK
>UniRef100_A0A8J5ZP01 EF-hand domain-containing family member C2 n=1 Tax=Galemys pyrenaicus TaxID=202257 RepID=A0A8J5ZP01_GALPY
RTVRTASTNRQNCdEQQQGEaAAERVIPRLCCDLFFVSHRWSNCFLFHAIGTCIRRHRISLPPPD----------------DDQYYTVQHFNIGIDIVFYGRKFRIYDCDS
>UniRef100_A2DJ77 MGC84469 protein, putative n=1 Tax=Trichomonas vaginalis (strain ATCC PRA-98 / G3) TaxID=412133 RepID=A2DJ77_TRIV3
QeayTLRFYGYFQQSLtESPGETyriRYVNIYVYTEDDTVMIEEQKSRNSGMTQ-GVLLRRMRVQNPNaEPY---------------GST-YIVQDFQIGVNIDISGIVYHIYDCDQ
>UniRef100_L1K0H1 DM10 domain-containing protein n=1 Tax=Guillardia theta (strain CCMP2712) TaxID=905079 RepID=L1K0H1_GUITC
KVLRYYGVYVDTVdPSVIGSapldaqvrdnnfvHECTILYYLEDGTMQVGEKRQDNSGMMQ-GQVVKRTHVPKPIyneegwilpnpneaPNGTA----------SLLNDSssslssFYTPDDFEIGGEINIFGRLFYIFDCDQ
>UniRef100_A0A7S1XS94 DM10 domain-containing protein n=1 Tax=Phaeomonas parva TaxID=124430 RepID=A0A7S1XS94_9STRA
KVLCFQAYCIEDIEESNletqRVRRFDIYYYLTDESIEVYETRQKNSGM-PQGCFIRRHRIPKmDqgnaaaedD-----GGGFFIQSvsgagasasgpatglapplqprsifgegatgdnESAASSLDrpkrYFGLADLYVGAELPIYGKTFTIVDANE
>UniRef100_K8ERE1 DM10 domain-containing protein n=1 Tax=Bathycoccus prasinos TaxID=41875 RepID=K8ERE1_9CHLO
IVLRFFAKYTEIVHDSAtetsRERRVVFRVYAEDLTIDATEPKQENSGL-QQGLYLKRTKCEEvfseqlrEalvvksneI-----GGGD--------TAAEvkRVVLEMLKVGNTITVCGRAFSVYACDG
>UniRef100_C1EF39 DM10 domain-containing protein n=1 Tax=Micromonas commoda (strain RCC299 / NOUM17 / CCMP2709) TaxID=296587 RepID=C1EF39_MICCC
RVLRFFGTCEvpaggDDARLVGSTRNFVVHYYLADDTVEVLEVMPGNAGREPYGKFLKRQKLPRATLAGGgyrygvGIRPasDETLRARRREPDGFYHWRDFRVGEDVVVFGLVLTLRDCDE
>UniRef100_A0A8D8Z5S8 EF-hand domain-containing protein 1 n=1 Tax=Cacopsylla melanoneura TaxID=428564 RepID=A0A8D8Z5S8_9HEMI
-------------------ITYDINYYLVDNTMEVLERHRPNNGRVPYPKLLARMRMPKDYRALlkssIGSQDEADSRLDQQDSSDYYGPKDLIVGSTLNVLNQSLYIVDCNE
>UniRef100_A0A1D1VGK2 DM10 domain-containing protein n=1 Tax=Ramazzottius varieornatus TaxID=947166 RepID=A0A1D1VGK2_RAMVA
QVLCFEVVVDESIQKHGDIRRMVLKYYVYDDTLELLQLWEKNSGYDPARAVIRRQKIPKDFFN------DLVLQIGDKTTPTHYTVRDLKIGETLLLFGKKVTICDCDE
>UniRef100_A0A7R9RJV4 DM10 domain-containing protein (Fragment) n=1 Tax=Argulus foliaceus TaxID=509924 RepID=A0A7R9RJV4_9CRUS
LAMKFMAYFIDGDetkpDVLCHLRHVFITYFPYDGTMSIYEPEEDNSGL-MQGKLLRRMKVPRDGK------------------AGHYDWSDLNVGVDLKIFGRVYHIYDAEK
>UniRef100_A0A096P7G7 DM10 domain-containing protein n=1 Tax=Ostreococcus tauri TaxID=70448 RepID=A0A096P7G7_OSTTA
VILQFRAAMVPFdgvgDVsEFDTARQFVVSFHVSDKTISIFEQASKDACS--SK-FLERARVRNVDN----A--------------QFYDVADMRIGSVLKIHSRAFKLYESDL
>UniRef100_A0A0G4E8Q6 DM10 domain-containing protein n=3 Tax=Vitrella brassicaformis TaxID=1169539 RepID=A0A0G4E8Q6_VITBC
KMLRFEGRVVN-GQKEDERRRFIIGMRLSDEAMGVWELRCRNSGHTEGK-FAELGRKKNPMA----PAGP---------RPSFYKPEDLFVGATIFVSATPFYLIRADE
>UniRef100_A0A0P1AR03 Uncharacterized conserved protein, contains DM10 domain n=1 Tax=Plasmopara halstedii TaxID=4781 RepID=A0A0P1AR03_PLAHL
EVLRFRGRFET-DQPENIARRFVISITVSDQSVSIIELAQRNSGIVGGK-FLERTRIKRTRQ----DGSVVM----TNGQTSWLNLNDFYIGARVRMAGQIFLLFEMDE
>UniRef100_A0A1Q9C6Z0 EF-hand domain-containing family member C2 n=1 Tax=Symbiodinium microadriaticum TaxID=2951 RepID=A0A1Q9C6Z0_SYMMI
EVLRslgarsFECKMIN-GEPEDELRARdlsvlkwsCFMRLPAGSEADSVKVPVRNSGHMGGK-FADKRRIKNPDT----G--------------LPFQLSDFYVGKVVTIAAQ--QITRADE
>UniRef100_A4S6M0 DM10 domain-containing protein n=1 Tax=Ostreococcus lucimarinus (strain CCE9901) TaxID=436017 RepID=A4S6M0_OSTLU
IVLQFRAEMVPIsdadEVcEFDASRRFVVSFHVGDKTLSIFEQASKDSCS--SK-FLERARVRKRDE----TG-------------AFYDLRDMRVGSVLEIHSRAFKLGESDE
>UniRef100_A0A1W0WG49 EF-hand domain-containing family member C2 n=1 Tax=Hypsibius dujardini TaxID=232323 RepID=A0A1W0WG49_HYPDU
EVLRFFAYWDDRERLFGDRHHLVIHYYLGDETTEVVRKVPMAYGKQRLEPFVRRCKLPKHAKDYEkvnlgSPWPVLNIvcsnpkrpETSKFTVrpssTETYTEVDLRCGETVNIFSRPVFIYDCDA
>UniRef100_A0A139AGH7 DM10 domain-containing protein n=1 Tax=Gonapodya prolifera (strain JEL478) TaxID=1344416 RepID=A0A139AGH7_GONPJ
TVLRWRAKLRSDK-MVDRDREFVVGLYMQDETISVDETTH-ASGMSSGR-FLKRSRIPKhpippsgsgsGE-----------SEDDGSGAHEYHGTKDFAVGKVIELHGRVFEITACDV
>UniRef100_A0A6H5GAF4 DM10 domain-containing protein n=1 Tax=Nesidiocoris tenuis TaxID=355587 RepID=A0A6H5GAF4_9HEMI
KILRFSAIMLSKD-PVYHGRKYIISYFLADDTINIHDGETaPNTGVNGGM-LISRRQILKPG-----------QDIYSSKTPQYYDYRDLFIGNYLELEGHSFHIVGADE
>UniRef100_A0A6T8IHZ0 EF-hand domain-containing protein n=2 Tax=Hemiselmis andersenii TaxID=464988 RepID=A0A6T8IHZ0_HEMAN
IIFRWKAKFDMDkmghaG-PDDSKRRFVVSFFMADSTIAVYEPPVSNSGFVGGK-FLERQKIRKhgTG----------------QHESVYLSEEDVLVDlpATIWINGYPMMLLECDR
>UniRef100_T1G564 DM10 domain-containing protein n=1 Tax=Helobdella robusta TaxID=6412 RepID=T1G564_HELRO
NVLRFAARIPQN--NIDSDREFVVSFFLADDKMMVFERTFKNSGLQAGK-FLEKSKVMKPGY----------KQRYLNKLPDYYELTDMKVGHRILVNGLWLLLHDADD
>UniRef100_UPI0020957CF2 EF-hand domain-containing family member C2 isoform X3 n=1 Tax=Caretta caretta TaxID=8467 RepID=UPI0020957CF2
NLLRFLAKFITDN-PIDKDRQFIISYFLSDDTISVFETPQRNT---GGS-CVEDD-----------------ERNMSEHAGDSILNIQDFEDYPPLRSPSFSIVSEFSA
>UniRef100_A0A7S1KZ99 Calmodulin n=1 Tax=Neobodo designis TaxID=312471 RepID=A0A7S1KZ99_NEODS
KVLSFSGLWNDEEAAPGgILRTLDVRYFVEDDTILIIEKPNpVTKTESVQATFLSRRRLPVSGKTtksVELTFAGRINGQRDAFLghnDRYVSAQDLYIGAEINVFGRIVKLFDCDG
>UniRef100_A0A553NPK8 DM10 domain-containing protein n=1 Tax=Tigriopus californicus TaxID=6832 RepID=A0A553NPK8_TIGCA
QVLRFFTYFTEMILDqGVerdRIRKCHLLFFLEDDSIQILEPTFSNSGI-PQGTLMRRHRVPFTYVKDRELGP--TRSYHRTCPKPHITYRDLNLRQNILIYGRLHRIVDCDT
>UniRef100_UPI0012D4AA5F EF-hand domain-containing family member C2 n=1 Tax=Contarinia nasturtii TaxID=265458 RepID=UPI0012D4AA5F
KILCFKAYFRQNLVGsSGsaqfQIRKVKILFYMEDGTIQVVEPRTDNSGI-PQGCIVKRQRIPCSSS----------------TQNQCLSMLDLNVQKEVEIFDRIYIITDCDG
>UniRef100_A0A7S4D451 Calmodulin n=1 Tax=Eutreptiella gymnastica TaxID=73025 RepID=A0A7S4D451_9EUGL
RVLTFLAGWDDRDRPHGDLRLMQINYYLEDATIQVLEPPVTNSGREECKKTLVRQRIPRKSPDNKPAFKNESLLdHlktDAHQhntfgvnmDGGYLTEDDLGIGRVLDIHGKTFVLYDCDE
>UniRef100_A0A0M9FRV0 EF-hand domain-containing protein n=1 Tax=Leptomonas pyrrhocoris TaxID=157538 RepID=A0A0M9FRV0_LEPPY
KVLRFYAFFNEHATEGGAadywHRKVVITFYIDDDTFMIFEPRTFNSGLDGG-TFLKRQKVVADPRQ-REQHPN----------DEYVSLNFLNVGQSVRLNAVDFFIYDCDP
>UniRef100_A0A0S4IJW8 EF-hand domain-containing protein n=1 Tax=Bodo saltans TaxID=75058 RepID=A0A0S4IJW8_BODSA
KVLRFFAYVTESVRESATeairHRRLTITYFPADDSLLIQEPHLPNSGLPGG-TILKRQRVPTNPRQ-REALPE----------QEVVTLDHLRVGESVMIHSTIYNVYACDA
>UniRef100_A0A059LJA9 DM10 domain-containing protein (Fragment) n=1 Tax=Helicosporidium sp. ATCC 50920 TaxID=1291522 RepID=A0A059LJA9_9CHLO
HVLRFFCLWNDSGSLFGDWHRLRLHYYLEDDSVELVEDQEAG-GK--SKIFLRRAHVPAGPRSAA-------MQ-SGMNKPVNLAPREILPGRHVNVHGREFFVYDMDS
>UniRef100_F0W5B4 Uncharacterized protein AlNc14C20G2080 n=1 Tax=Albugo laibachii Nc14 TaxID=890382 RepID=F0W5B4_9STRA
KVLRFDVSWHDDHPLYPELRLYTLHYYLEDHTLEVVEPkiERNFTGRGHFALLVSRQRARRDGKDWSstlSSPPSTEAE-------PTITERELICGRTIRIHSRDFVLENCDD
>UniRef100_A0A7S0LWK4 DM10 domain-containing protein (Fragment) n=1 Tax=Cryptomonas curvata TaxID=233186 RepID=A0A7S0LWK4_9CRYP
KILRFIAICTDyVPESLGDpvrNRQYTIQYFLVDDSIQIVEQKTTNSGYVQ-GVFMRRHRVPKHGG------------VSSGNDGDFVSIRDFVDTNEVLIYGRNFQLIGCNN
>UniRef100_A0A7S0PD96 DM10 domain-containing protein n=1 Tax=Cafeteria roenbergensis TaxID=33653 RepID=A0A7S0PD96_CAFRO
KVLRFDCLWRDD-REGGDTLHYVLQWHLKDDQAELLEVHDRNDGRDPTNVAVSKRRLPLKWRAT-LRMPG---DMTAEAAENWATPSDIRVGSTLDVFGRNLFVRGAD-
>UniRef100_A0A087XSD1 EF-hand domain (C-terminal) containing 2 n=1 Tax=Poecilia formosa TaxID=48698 RepID=A0A087XSD1_POEFO
NVLRFKARMMTT-DPVHRGRVFLITYFLSDDSLSVFELEQKNSAICTK-IFALKSRLKIPAI-----------SLIVFSISIFMVKNEMNAGLWVWNKSQEFKKCSANR
>UniRef100_A0A0R3T2E6 DM10 domain-containing protein n=1 Tax=Rodentolepis nana TaxID=102285 RepID=A0A0R3T2E6_RODNA
DILHFMTRIISG-NEDAESRKFVLTCFPCDNTFMIQEPEIENSGFKSG-KYMERCKVLKPGQ-----------SVANTELPEYYSPSDVYIGAHLVINGVTFEICDADV
>UniRef100_A0A0R3VWX5 EF-hand domain-containing family member C2 n=1 Tax=Taenia asiatica TaxID=60517 RepID=A0A0R3VWX5_TAEAS
RLIAGVDDDgnCGR-EEITRRRIFIISCFLRDNTFMVYEPPVTNSGYKGG-KFMERRKVMKPGQ-----------PIFRTHLPSYYAPSDICIGGQVIFNNFVFEICGADE
>UniRef100_A0A6P5P9M2 EF-hand domain-containing family member C2 n=1 Tax=Mus caroli TaxID=10089 RepID=A0A6P5P9M2_MUSCR
ERSEELQvsqgldlnnwkggeemQPLDR-QDYSYNRFGSKNTSSSLEQLEMPIRYEMKMGNAGG-MFLKRSRVKKPGQ-----------EVFKSEFSEYIKAEELYVGATVNINGYLFILLNADE
>UniRef100_A0A7E6FGY6 EF-hand domain-containing family member C2-like n=1 Tax=Octopus vulgaris TaxID=6645 RepID=A0A7E6FGY6_OCTVU
RVMCFLAKMLTK-DCSVSEQDFIINYYLADDTIQITLKGGANSGVKTG-IFLGRGRVKLPNQ-----------QKFNIEPTKYYCANDFNIGAIVQLNHYVYRIVDADE
>UniRef100_A0A8J2Q0S8 DM10 domain-containing protein n=3 Tax=Allacma fusca TaxID=39272 RepID=A0A8J2Q0S8_9HEXA
DILRFDAKFYCPLQKVNAARRFTINYYMSDDTIQIFEKEHPNVGLPKG-NFLVRCEVKKPGW-----------QPEVGLDPEYYAPGDFYVGAILDINSFKFQLLSADE
>UniRef100_UPI0006C97C22 EF-hand domain-containing family member C2-like n=1 Tax=Copidosoma floridanum TaxID=29053 RepID=UPI0006C97C22
RVLRFAAKMISD-VPANADRCFVVNVRLFDNAVSIPEIVCERKGRNKS-MFQQYARARLPGQ-----------NVFTSEEPRYYEPRHFYIGATVTLYGFKFQLVGADE
>UniRef100_UPI0022B49A15 EF-hand domain-containing family member C2-like isoform X1 n=2 Tax=Galleria mellonella TaxID=7137 RepID=UPI0022B49A15
HTLRFAARLIND-NPEDARRYFIIKYFLCDDTIGVFELCERNSGFKGG-KFFRRDKMYLPGV-----------EFFVPKEPPSYTDKDMWVGNELVINKHRFRLVAADE
>UniRef100_A0A7S1I0S4 DM10 domain-containing protein n=1 Tax=Eutreptiella gymnastica TaxID=73025 RepID=A0A7S1I0S4_9EUGL
-VLAFNAVWDDTQNPHGDLRRFNIKYFLCDDTIMVMEKFPPNSGRDPVASFSTRRRVPKDEEAKS-HMHDLTFKrAGGYKCGSFYEVGDLGINKTIKVNGCVLKMVDAD-
>UniRef100_A0A836CI01 Protofilament ribbon protein n=1 Tax=Tribonema minus TaxID=303371 RepID=A0A836CI01_9STRA
SVLRFTARLDTPF-EEDVGRQFVITVYGADNTVAVREPPRPNSGFWGGT-FLTRSRARREAGGSGSSSAGGARGGGGDDVHLCLQDFACGVGGLVHMNGHPFRLTGADE
>UniRef100_F0YD55 DM10 domain-containing protein (Fragment) n=1 Tax=Aureococcus anophagefferens TaxID=44056 RepID=F0YD55_AURAN
NVMRFSIKMANAR-DEDKQRIFTLQYYLIDDTMAIREPPLRNSGHIGGN-FLSRSRVRKPEVeqtNAPAPAP-AGAVWGPAPVTAYYGAEDLHVGNEIEFLGHKFTIYEADE
>UniRef100_F0YI14 DM10 domain-containing protein n=1 Tax=Aureococcus anophagefferens TaxID=44056 RepID=F0YI14_AURAN
GVLRYQAAFANPK-PEDRGRLFVLVYYSTEFALMIREPPRRNSGVVGGN-FLAKMKLKHPDG-------------------KLVTAADIAVTQLYTRLANVAWSDEDTR
>UniRef100_U6M7B3 EF-hand domain-containing family member C2, related n=1 Tax=Eimeria maxima TaxID=5804 RepID=U6M7B3_EIMMA
QKPPPLELTEQPfsgnaVENS-RRRFCIISFYLEDGTLSVYESTTDYGETRQG-PILKRHKMPRADGS------------------GFVTFTDLKLGAELELYGRVFLILECDE
>UniRef100_A0A8T0ENR9 EF-hand domain-containing protein 1 n=1 Tax=Argiope bruennichi TaxID=94029 RepID=A0A8T0ENR9_ARGBR
KVLKFYGIWKNDPQRPPAVRRIVLKYYLVDDTLAVFENYPPSSGWGPLlsvlqgpmdvassggsfMTLIRRQRVLLDRPKDVEKL-PCYLEPRDTDDITWIKPEHLKTGEDLKILGKTFFLGKADE
>UniRef100_A0A8X6GAP6 EF-hand domain-containing protein 1 n=1 Tax=Trichonephila clavata TaxID=2740835 RepID=A0A8X6GAP6_TRICU
KVLTFYGIWKNDPAKPPAVRRLVLNYFLVDNSLQVVHNPPPNSGWTTLmsakadiakgevssNIIIKRQKVLLDRRKEVEKI-PFYFEPKDIDDITWIQPEHLKTGEDIIILGKTFYFGKTDD
>UniRef100_A0A8K0AJB6 Conserved mitochondrial DUF1126 domain-containing protein n=1 Tax=Andalucia godoyi TaxID=505711 RepID=A0A8K0AJB6_ANDGO
-VLRFFALWDDRRRTGGALHNLVLSFYVQDETLEVADMFfNEFSKRYSSQALLRRQKVPRDPKSLE-KQTNLVTALSprrnEENKKMYVTAKDLMVGHLVDLLGRKILIYDAS-
>UniRef100_A0A482WKI9 DM10 domain-containing protein n=1 Tax=Laodelphax striatellus TaxID=195883 RepID=A0A482WKI9_LAOST
KCLAFQGYFKECVplpnmdDDNYRIRHVNIVYFLEDDTITVIEPTVQNRPLKLrpsPRQTCETKQNPKNDE------------------GDFWHWKDLNVGIDMNLHGIVYRLCSCDN
>UniRef100_F0YI14 DM10 domain-containing protein n=1 Tax=Aureococcus anophagefferens TaxID=44056 RepID=F0YI14_AURAN
---------------------MDTQMLEGSSSLSCYESLNEell-PQLP--GYRCNRHSAGNRNQTIK-------------YINRHMFLTAAKNVEPYDQYGRIFHVNGCNE
>UniRef100_F0YC17 Calmodulin n=1 Tax=Aureococcus anophagefferens TaxID=44056 RepID=F0YC17_AURAN
EVLRFFCAYQDDRRDGDRDRRYTMHYFCTDDTIEIKEVATE--GVQRFPNLLRRSRLPKEAFWNP-DNPLV----DNNEP-RQVNWKDLKCGGSLLVWGRPLLMLSCDR
>UniRef100_A0A4P6D9F9 Putative ef-hand domain-containing family member c2-like protein n=1 Tax=Rhodnius prolixus TaxID=13249 RepID=A0A4P6D9F9_RHOPR
HVLVFDSYYlqklDDTTSDNYIVHQCKIYFFLEDGTIKVVEQRNPfHDGL-SSGCIIHRQRIRYPAE----------------GSEDFYDILDLNIGNDVEFFGKLFRLIDCDE
>UniRef100_A0A7R9RJV4 DM10 domain-containing protein (Fragment) n=1 Tax=Argulus foliaceus TaxID=509924 RepID=A0A7R9RJV4_9CRUS
KVLRYRLETETVL-PQVPQRTVLLLYYLADDTACLKEPGA--KSDVGKT-FHKRGALRKFhpdstS--------------LTAVYDGIYTPQDFSPGALVQVGNHRLHITDADL
>UniRef100_A0A851D7R3 EFHC1 protein (Fragment) n=1 Tax=Todus mexicanus TaxID=135184 RepID=A0A851D7R3_TODME
KVLRYQLALVSAF-LDGIE-------------------------------------------------------------PAYAEDNTAFFNSSSPVFGHRFVITDADE
>UniRef100_A0A8C6WZT9 EF-hand domain (C-terminal) containing 1 n=1 Tax=Neogobius melanostomus TaxID=47308 RepID=A0A8C6WZT9_9GOBI
KVLRYKAKLESPY-SIDEDRSFVLSYFLTNDMISIYEKSARNTGVMGGK-FLEKTRIPKPG--------------SSAENPQFYTPADLALGATRNfigiLYNSIMYLLSIHP
>UniRef100_UPI000A1C1DD4 EF-hand domain-containing protein 1-like n=1 Tax=Boleophthalmus pectinirostris TaxID=150288 RepID=UPI000A1C1DD4
KILRYR-----------------AKLKPQQVQGESKTKSSSRKFELGVT-TEKTGYLPGED--------------LEITTRITNKSKDTKVTPRYVFYGEQSVFSKDKK
>UniRef100_W6LC24 DM10 domain-containing protein n=1 Tax=Phytomonas sp. Hart1 TaxID=223615 RepID=W6LC24_9TRYP
-VVQLLAYFVENIqqNPtdEKHIRKVCIKFFMEDDSISIIELKEANSGIVQGTIL-SRRQVPKKSDD----------------DKKLVLLKDLKIGNEVLIYGINYHIIDMDR
>UniRef100_A0A146KLI5 Flagella associated protein (Fragment) n=1 Tax=Trepomonas sp. PC1 TaxID=1076344 RepID=A0A146KLI5_9EUKA
-VSRFYAWFAtEvqeSQAEKMRIRHCIIDFVELDGTLLIYERPLQNAGY-SQNELLKRQKVLRDFRNENSG---------------FITLDDLKVQHSIDIYATKYNIYACS-
>UniRef100_A0A4Y2GAP9 EF-hand domain-containing family member C2 n=1 Tax=Araneus ventricosus TaxID=182803 RepID=A0A4Y2GAP9_ARAVE
KSLHFYGIYTRTETQFEEKCYVSLYYQLYDGKIKIIDDKKMSehqvcpvKGGQKSYILLKPTHVPKKLSI--RTFDkigdgRTILNLSAkikdtrfkrvlmtaqdmggflpdsnplkhDPMAEYYKPEDLDLGKTFDVFGAKVFLYDCDE
>UniRef100_UPI0015AE0AB8 EF-hand domain-containing family member C2-like n=1 Tax=Stegodyphus dumicola TaxID=202533 RepID=UPI0015AE0AB8
NVLHFFGIYERSASHLEDKRFISLYYSLTDDTIKIVDAQKIPeykhclrNGAYDNYVILRPTRVPKNMTQ--INFPgdicdPVVLNLSAknkdtrlrelllssqnkmdkgafitdsnplleEKNSiQYYSSKDLDLGTAINIFGARVYLYDCDE
>UniRef100_UPI0006C9B7CF EF-hand domain-containing protein 1-like n=1 Tax=Trichogramma pretiosum TaxID=7493 RepID=UPI0006C9B7CF
KTLTFDAKWED--------KLYKIRYFLNNHTVSIAAVGKGER-----GLLLHKSRVPRKEVD----KPNAYFQSSAGGDRSYLCPTDFKVGETVEIFSRQFYIFDCDQ
>UniRef100_A0A6L5DH18 DM10 domain-containing protein n=1 Tax=Ephemera danica TaxID=1049336 RepID=A0A6L5DH18_9INSE
RPLRYALRM-DTERPNDQNRRFVLIFEPRRGVATINELPGHNTGITSGR-FLGPIKLVKQarpGSP--------------PpIQPRYYGPQDFGIGEVVVASGQRFVVTSAD-
>UniRef100_A0A1Y2BSC3 DUF1126-domain-containing protein n=1 Tax=Neocallimastix californiae TaxID=1754190 RepID=A0A1Y2BSC3_9FUNG
-ILRFFGYYKESTYqSYeqYHLRKVVIYYYLEDNTMRVNEPQVENSGI-PQGILINRQKIPKYVRyykeiekidlnptemmpedpyqlerkrplrikSnEQKNYPLTnFLEYDrkvlrfycvwdnriDIESSEKYRWSDFKIGSVINFLRRKCLIYDCDE
>UniRef100_A0A8R2A5W5 DM10 domain-containing protein n=1 Tax=Acyrthosiphon pisum TaxID=7029 RepID=A0A8R2A5W5_ACYPI
EVLTFYAFYKKSGRGssAgikYTLKQLKIIYFLVDETIQVNEPTKQNSGG-PQGCFIKKQKIPLP---------GCD-----QETGPYYRLPDLVVGTTVIFHGKELRITGVDA
>UniRef100_A0A5J4UZN4 DM10 domain-containing protein n=1 Tax=Streblomastix strix TaxID=222440 RepID=A0A5J4UZN4_9EUKA
----VLELKDCIFAPSGSTGSMLAPFDCSSPLLLFADARDTYSAENAHSQTCllKGRRWNS--------------------------------------------------
>UniRef100_A0A0H5R6L4 DM10 domain-containing protein n=1 Tax=Spongospora subterranea TaxID=70186 RepID=A0A0H5R6L4_9EUKA
KVLRFTAYFRQAIQesqiETHRICPVAILFYLQDGTIRITETREDNNGM-QHGAILQRHRMPLSEtgyayD----------------GDHQFLSPEHIRIRRDLTLYSRVYRVVDCDQ
>UniRef100_A0A812P1E0 Calmodulin n=1 Tax=Symbiodinium sp. KB8 TaxID=230985 RepID=A0A812P1E0_9DINO
-MLTFFMYFKEPVPESGrenhRVRFLRLIYFLEDDTAQIFEDRVANSGI-PQGKFLQRQRVPLPTAMHGPKassgsglgtATIQSLGSGGGtASGNYLHWTHLYVGQELALLGRTFKVYGADD
>UniRef100_A0A8X8BVI0 EFHC1 protein (Fragment) n=1 Tax=Polypterus senegalus TaxID=55291 RepID=A0A8X8BVI0_POLSE
-------------------------------------------------------------M------------------VVVCSLDSHSSDVTYLVAQFNQIITLSEK
>UniRef100_A0A8J1ZX95 Calmodulin n=1 Tax=Amoebophrya sp. A25 TaxID=1410381 RepID=A0A8J1ZX95_9DINO
KICRFQAVVNDMYTEMYERRHFLIDYYLQDDTLAVHEIASPerlsgWSGREP-SIWFRRGKCRRAEAKHC-IKEGLL---QPLEDEECIALQDFQVGKTILLNGQEFYIYDA--
>UniRef100_X6NU41 Protofilament ribbon protein of flagellar microtubules n=1 Tax=Reticulomyxa filosa TaxID=46433 RepID=X6NU41_RETFI
KTIIFLAKLVDKIRA-NQQRRFLIQFYLEDETVRVYQKPLRNSGFIGGKFL-ERSQ------------------VINPDKKKLFHCEDFYVGAVLNINGFVFQLLETDP
>UniRef100_A0A8C1HIC8 EF-hand domain (C-terminal) containing 1 n=1 Tax=Cyprinus carpio TaxID=7962 RepID=A0A8C1HIC8_CYPCA
QVLRFYGYFRQevlhsPDEHF-RIRPVVIYYHLEDDSMCVTEPPVEKLWNSTGK-ADQTSE---------------------------LVWNGLQDNTLRRLH--TGTHTHTDS
>UniRef100_A0A7S1QMQ4 DM10 domain-containing protein n=1 Tax=Neobodo designis TaxID=312471 RepID=A0A7S1QMQ4_NEODS
ATVKFQLGLEGAS-PNDELRRFVLTFFLADTTIAIFESVQRNSGILGGK-FLQRQKVVNA---E----------------TGkPFVASDFYLGAKVTVNKFRFHVASSDE
>UniRef100_A0A1I8D414 DM10 domain-containing protein n=1 Tax=Rhabditophanes sp. KR3021 TaxID=114890 RepID=A0A1I8D414_9BILA
-ALCFTVYTNESDGPYQEllkIREMKLIYHLDDDSFSLFEKKTNNSGYIQGR-LFRRQKVPKAIKRIG---------------NDHLSWRDLNIGEDLNIFGQTYHITSCDE
>UniRef100_A0A2J8AG10 EF-hand domain-containing protein 1 (Fragment) n=1 Tax=Tetrabaena socialis TaxID=47790 RepID=A0A2J8AG10_9CHLO
--------------------------------------------------------AIKDDGS-P------------------LRWPDLRVGREVALYRRSYTLLVADA
>UniRef100_A0A5A8D3U1 Uncharacterized protein n=1 Tax=Cafeteria roenbergensis TaxID=33653 RepID=A0A5A8D3U1_CAFRO
NVLRFSVLWDGAKTrgdPLAVRQRLSLVYYLTDGTVEVLRLKPPGANRQSLPAkFLLRARLPRKIIIHDDRARSCEDGTGD---EDYFNETDFRVGDTITVHSMPMLIYDCDG
>UniRef100_UPI001EEAEF97 EF-hand domain-containing family member C2-like n=1 Tax=Daphnia pulicaria TaxID=35523 RepID=UPI001EEAEF97
LTLRFDGFYFEDSLAWGysrrAVHPVKLCYYLEDDTISVHEPVTPNSGRP-QGKLVRRHKV-FK---------------SGHET-KdedgrggrddespdkYWHWKDLNVASDVDIFGRRFRLTNCNQ
>UniRef100_A0A0G4GBL8 Calmodulin n=1 Tax=Vitrella brassicaformis (strain CCMP3155) TaxID=1169540 RepID=A0A0G4GBL8_VITBC
VILRFTAKLRDPK-PEDREREFVIAFYLSDDTLMIHEPPKRNSGI------VQGRFLQRGKY-------------FNEATGKNFGPRDFQEGDGVKVSGYWFDVKGMDT
>UniRef100_A0A0G4HB78 Calmodulin n=1 Tax=Chromera velia CCMP2878 TaxID=1169474 RepID=A0A0G4HB78_9ALVE
RnkALTFKAVLISAY-PEDADRAFIVTFYPNTDETQVHEETVRNSGF------SGGRFLQRGHH-------------LNGETGQRFKESDFRVGNEVTIRSAKFLLTEMDE
>UniRef100_A0A6H5J7M8 DM10 domain-containing protein n=1 Tax=Ectocarpus sp. CCAP 1310/34 TaxID=867726 RepID=A0A6H5J7M8_9PHAE
-FLRMYIRWDEDESVISgpaTVHRYILHYFLEDGTIEMRELADIKGGnyfEGRFPVMIRRQKVFKGGSTPslsvdriggdraiaaAAttprsarrvngggassgigsggSFFsdrggtgggGCRDDLG-DDLGETLSPLDLVVGRQVLLMKRPMVVCGWD-
>UniRef100_A0A5A8ELD7 Uncharacterized protein n=1 Tax=Cafeteria roenbergensis TaxID=33653 RepID=A0A5A8ELD7_CAFRO
-RLRFRGAVQDPRPFAPEHKVVLT-VFPEDDTVSIVEVYGNNKGYDGTSaKLFKRGRLPRRFVVH--DDRTRSIE-DDNGDEGYFTTAEFRVGALINVMGRNVRITEADE
>UniRef100_A0A812P1E0 Calmodulin n=1 Tax=Symbiodinium sp. KB8 TaxID=230985 RepID=A0A812P1E0_9DINO
-ILRFKGLWDDTDKVYGQKHYVNV-RYHLADAI------------------YKRAPLPLDDTFQ--DARSRDIE-DDVGKDSYVTwrHPSLRVGQFLNVMSRPVFLYAADD
>UniRef100_UPI001588C49D EF-hand domain-containing protein 1-like n=1 Tax=Chelonus insularis TaxID=460826 RepID=UPI001588C49D
KKLRYLASMVAV-HPEDKDRDFILEYNLADGKIKILEIGKRNSGHRAGC-FLASMYVPKPSSFQ---------KQDDTDDIIYYGPEDFYIGAKINIFNHQFIIKGAD-
>UniRef100_A0A1J4JHU3 EF hand family protein n=1 Tax=Tritrichomonas foetus TaxID=1144522 RepID=A0A1J4JHU3_9EUKA
TILQFSATINSRR-PEDKMREFVIAYYLEDQAFSVAEKRVPNSGFGSG-QFLKKTVVNNPKT------------------GKPYEPREVYVGAVIDMGGWQFTLQEAS-
>UniRef100_A0A1J4JHX6 EF-hand domain-containing protein n=1 Tax=Tritrichomonas foetus TaxID=1144522 RepID=A0A1J4JHX6_9EUKA
TVLSFTGKIVSNN-TDDNLREFMVNFCVEDSTFAVYEKVIPNSGFPGG-KYLKETKATCPDT------------------GKPYSADDVYVGSVIVVNGWRFKLVDAS-
>UniRef100_A0A1J4KC64 RIB72 protein n=1 Tax=Tritrichomonas foetus TaxID=1144522 RepID=A0A1J4KC64_9EUKA
TYLVFVASMYSDY-DEDKDRVFMVQYYLSNKTIAIFEKKDLKRGINGG-RFLARMALVDPRT------------------GENYDDDAFYVGAKIQAAGRIFELLDAP-
>UniRef100_A2DAZ3 DM10 domain-containing protein n=1 Tax=Trichomonas vaginalis (strain ATCC PRA-98 / G3) TaxID=412133 RepID=A2DAZ3_TRIV3
ENLVFNAKMITEN-PEEKARVFSISFNLREKKLSILEGK-SSFCISPQ-RFLSPSTVIDPTT------------------KSPYTESSFYIGSRIIAAGRLFELVDAS-
>UniRef100_G5C574 EF-hand domain-containing family member C2 n=1 Tax=Heterocephalus glaber TaxID=10181 RepID=G5C574_HETGA
QVLCFDVYLEDKVhdksQEIYRIRFYKIYFYPEDDTIEVYEPQVKNSALTQG-TFIQHHRISLPPPN----------------DDQFYTVYDFSINTDIIFYGWTFKIYDCDK
>UniRef100_A0A183U1W7 DM10 domain-containing protein n=1 Tax=Toxocara canis TaxID=6265 RepID=A0A183U1W7_TOXCA
--------------------------------------------------MLHKISYSSQEHIV---------------SRHAIH-----ILSDWLFVG----------
>UniRef100_A0A556U8V6 EF-hand domain-containing protein 1 n=1 Tax=Bagarius yarrelli TaxID=175774 RepID=A0A556U8V6_BAGYA
KVLRFYGYFQQEVlhsaEECWRVRPVVFYYYLEDDSMCVMEPEVENSGIQQG-KLLKRQKVQTPVYFLS---PTQ--TMRHMIKGLNYHIAHNAQGCDVTHIQD---------
>UniRef100_A0A1Y1MUG1 DM10 domain-containing protein n=1 Tax=Photinus pyralis TaxID=7054 RepID=A0A1Y1MUG1_PHOPY
KCLTFKAFFKQSVvespLEYYRVRKVNIIYFLEDDTITIMEPRIRVC--LRN-VFITCCYIV---L------------------HRIVAWSKDVLSDEVKYPKIISGITGTGK
>UniRef100_A0A6S7FSU3 EF-hand domain-containing family member C2-like n=1 Tax=Paramuricea clavata TaxID=317549 RepID=A0A6S7FSU3_PARCT
QVLCFDAYFQEAVHEkreeQYRVRRK----LRKDPEVLADYDAIIKDQLKTG-VIEPVAALEKPSD-----------------------------------------------
>UniRef100_B4DN08 cDNA FLJ57402, highly similar to Homo sapiens EF-hand domain (C-terminal) containing 2 (EFHC2), mRNA n=1 Tax=Homo sapiens TaxID=9606 RepID=B4DN08_HUMAN
QVLSFDAYLEEEVLDksqtNYRIRYYKIYFYPEDSERGCRTRRALTSlRIPRH-PETVPPV--SWQD-----------------------------------------------
>UniRef100_UPI00143F0CC1 EF-hand domain-containing family member C2-like isoform X1 n=1 Tax=Drosophila miranda TaxID=7229 RepID=UPI00143F0CC1
QVLCFN----ENLTEiyyaPYQVRKVRIYFYLEDGTMQVTVVTGHSAGLSGA-PSAHTQG-ANQGP-----------------------------------------------
>UniRef100_A0A6V7IHP7 DM10 domain-containing protein (Fragment) n=1 Tax=Bracon brevicornis TaxID=1563983 RepID=A0A6V7IHP7_9HYME
KKLRYLMSMLAV-HPEDQGREFILEYSLSDGTIKINELARKNSGRRAG-CFLASMQIPKKKLKID--------DCSEEETPIYYAPTDFYVGAKINVFNHRFVITGAD-
>UniRef100_UPI0021AA34F9 EF-hand domain-containing family member C2-like n=1 Tax=Daktulosphaira vitifoliae TaxID=58002 RepID=UPI0021AA34F9
------------------------------------------------------MVQAKNGKFLkPIGYDeeKQLLKVMgkSidtkyqwyaldsqhagySVENTYYNASDLYIGAQLFIYNRLIILTECDE
>UniRef100_A0A8R1Y3X6 DM10 domain-containing protein n=2 Tax=Pristionchus pacificus TaxID=54126 RepID=A0A8R1Y3X6_PRIPA
KQLHFTVYAQEKGneglgldRMAQRVRLLRLFYHLDSDTLSLYEPPQDNSGCMQGR-IFRSQRVPRPARV----------------GAPFLHWSELRLGVDVDLFGTKYRLARCDN
>UniRef100_A0A8S1GWI3 DM10 domain-containing protein n=1 Tax=Caenorhabditis auriculariae TaxID=2777116 RepID=A0A8S1GWI3_9PELO
EVLSFDAYTEEKGmdENIRRIRKYRLEYHLADGSVAIEEMSPTD----------RKTPSQLINDK----------------AVAHLRWSDFNVGNSVTIQEKSYRIVGCDQ
>UniRef100_A0A7R9AE29 DM10 domain-containing protein n=1 Tax=Darwinula stevensoni TaxID=69355 RepID=A0A7R9AE29_9CRUS
QVLCFEGLLEES--WERGHRAVKVLYHLEDDTIQVRESLSSPSHIPQ-GTIFRRQKMPKSS-------------------GGHYSLEDMNVGRRLDVHGRRVHLVDCDA
>UniRef100_T1J708 DM10 domain-containing protein n=1 Tax=Strigamia maritima TaxID=126957 RepID=T1J708_STRMM
-ILRFSAELANQT-LLSIGRKFVINVFLIDSKIMVYEVPQRNSGFAGG-KFIGKLKIKKAIDPNP---PA------GEISSHYYNASDFYIGAAIKLNNFEFRITDADE
>UniRef100_G0TSC3 DM10 domain-containing protein (Fragment) n=1 Tax=Trypanosoma vivax (strain Y486) TaxID=1055687 RepID=G0TSC3_TRYVY
KVMSFLAKLAKPLVPGDEKREFVISFYRETDEMSIFEKPEKNSGFIAGR-FLAKGIYRRPMPD---------------GSTVQYTPDDFQVGKVVTILERPFILLSMSE
>UniRef100_A0A8J5XPG3 Calmodulin n=1 Tax=Diacronema lutheri TaxID=2081491 RepID=A0A8J5XPG3_DIALT
-ALRFNASLAHA-SVDDESRRFVVSFFLEDGTLSVFEAREPNSGHVGG-LFLERTRVPLPRAHAGR---AAAVASSGRAGGAHYSAHDLTPGAELDLFGRKLVLHSADA
>UniRef100_A0A7S0XFR9 DM10 domain-containing protein n=1 Tax=Chromulina nebulosa TaxID=96789 RepID=A0A7S0XFR9_9STRA
KICRFEAYFNDSSKnNLIRTRIVNILYYLIDDTIEIIEPKVNNSGSIEGK-LLKRHKIKKINNKKsykslslspvKSsnrslySSPSrsTvnSLTtspikpltsysnnrvdnelsISssvsslTLNESDYYTIHDFHAGAELNFYNTIYTIMNCDN
>UniRef100_A0A0H5QI73 DM10 domain-containing protein (Fragment) n=1 Tax=Spongospora subterranea TaxID=70186 RepID=A0A0H5QI73_9EUKA
-VARFFAYQVG----HRFLRKFALYFYLEDGSMSMGEIPDqlqLNCGRPHrQVTFLRRHRVNLPGS------------------NRYYELRDFAVSKTVNLYARAFRLYDCDQ
>UniRef100_UPI001FB77731 EF-hand domain-containing family member C2-like n=1 Tax=Penaeus chinensis TaxID=139456 RepID=UPI001FB77731
-VLRFSAQLDTPD-NKDGDRNFIMIYHVADATLEIKELARP-GGL-GG-RVLSRSHVPKPQPKGDERGAG------RYAGEDVYTLNDLYIGSILDVWGRRYVLTGADR
>UniRef100_A0A7S4KE02 DM10 domain-containing protein (Fragment) n=1 Tax=Guillardia theta TaxID=55529 RepID=A0A7S4KE02_GUITH
KVLRFLATISDLVPEnfrsRRRERQFTILYFLVDDSIQIIEDTGEAV---SERIFMKRHKVLRSSTA----------NV--EDEQSFLSFYDFANTDRVVIYGRNFRLLACN-
>UniRef100_A0A8D8TPV9 EF-hand domain-containing family member C2 n=1 Tax=Cacopsylla melanoneura TaxID=428564 RepID=A0A8D8TPV9_9HEMI
RILRFNARRVSDQDDsKEFEFEYVISCYMADNTISVYKSSGQNSGCGS-GMIIGKRKLLKPNQSMR----------TINTYPEYYTYEDLYVGAQVEMDRFKFKIIGCDE
>UniRef100_A0A2C6L8U5 Efhc1 n=1 Tax=Cystoisospora suis TaxID=483139 RepID=A0A2C6L8U5_9APIC
KCLRFLARLVEPLVPGQKERLFCIQYYLGDEEVMVTELSQRNVGVAG-RKFLQRGKYVDDN-------------------GMHFKAEYFVLGAEVRINKHPFQIIDADR
>UniRef100_UPI001E67340C LOW QUALITY PROTEIN: EF-hand domain-containing family member C2-like n=1 Tax=Procambarus clarkii TaxID=6728 RepID=UPI001E67340C
KILRFGAKLVSSC-DIDKDREFVINFYVYDSTISVYEVPKINSGMRAG-MFLGRGLVVAGAGHVA-GA-------GHVAGAGHVGGQDLYVGAVVTINSHVFRVTSADQ
>UniRef100_F0YE10 DM10 domain-containing protein n=1 Tax=Aureococcus anophagefferens TaxID=44056 RepID=F0YE10_AURAN
EVLKFVVTWDDP-SPGGQQHEYKLCFYLSDSCAELCTSPQ--PGFDRFPHLLRRQPLPLNWDAIQRG-----------APPRHAAAEDLKIGATINVYNRILKLVDCT-
>UniRef100_A0A7S2CTV8 DM10 domain-containing protein n=1 Tax=Florenciella parvula TaxID=236787 RepID=A0A7S2CTV8_9STRA
RILRFKAKVANLHTgdMDPTSPVLIINYFLADDTLSVFEPVVRNSGMKGG-TFLNRMRYKKHITPKQGGGRNA-SSRRSGLLSRWFRPSDFVKGADVTFEmpstgcaVHRFKIIDIDP
>UniRef100_A0A6U9QV95 DM10 domain-containing protein n=1 Tax=Picocystis salinarum TaxID=88271 RepID=A0A6U9QV95_9CHLO
QVLCFTACLpnylDDQ-TPPDSARTFAIRYFLGDDTMEIIETSARKR-TDQFKKFLVRQLLPKKLA-----FNSEFIATDSprqFDGRLHVHWKDLRIGAYLWIFGREVLLTGVD-
>UniRef100_A0A1D1VWY0 DM10 domain-containing protein n=1 Tax=Ramazzottius varieornatus TaxID=947166 RepID=A0A1D1VWY0_RAMVA
-YYCFEV--VWDY--EGNIRQFVLRFFPLQESSELYDVMKH-------KTFMKRTRTSN------------------------LKLSHLNIGKTVSVLNRQLLVMNY--
>UniRef100_A0A1D2MSG8 Nucleoside diphosphate kinase 7 n=1 Tax=Orchesella cincta TaxID=48709 RepID=A0A1D2MSG8_ORCCI
-KLIFVMEWYDRG--ADLVKKYTLTYYGIDKSCEIVNRIIE-------NAFTRIkyksynpfnqCSnCyvwtDrsrqsqT------------------------LstttqsghgYSENLIVGNVINIYGREMTVTEY--
>UniRef100_A0A1Y1LGG1 DM10 domain-containing protein n=1 Tax=Photinus pyralis TaxID=7054 RepID=A0A1Y1LGG1_PHOPY
-RLSFLGDYFDYE--AALHKNFLINFYPCDNTVEIFDRDMN-------RIYLRRAACEG------------------------VQLNDMFVGNKIRIYGRQIDLTDY--
>UniRef100_A0A1Y1VRC2 Nucleoside diphosphate kinase n=1 Tax=Anaeromyces robustus TaxID=1754192 RepID=A0A1Y1VRC2_9FUNG
-RYCFNVEYYDNQ--AELIREYQLMFFPSDNSIEMYDVKQK-------KIYLKRVGYPG------------------------IQLRDLIIGATIIIFSRPLLIKSY--
>UniRef100_A0A1Y5IE73 nucleoside-diphosphate kinase n=1 Tax=Ostreococcus tauri TaxID=70448 RepID=A0A1Y5IE73_OSTTA
-RLSFRVEWYDSV--QERSYELVLRAYA-DGDVELIDEGKK-------RTFLRKCE-PdrT------------------------IKREDLYLGNVLTVYARRLTIKEY--
>UniRef100_A0A564Z649 DM10 domain-containing protein (Fragment) n=1 Tax=Hymenolepis diminuta TaxID=6216 RepID=A0A564Z649_HYMDI
-VYSFIVEWIKNE--SGAVERFRLNFFTDDNSVDMRYPRDN-------KLFLRRIVQPD------------------------IKLSDFYIGNTINVLSRRLYIVGF--
>UniRef100_A0A7J6N425 DM10 domain-containing protein n=1 Tax=Perkinsus olseni TaxID=32597 RepID=A0A7J6N425_PEROL
-----MVPWKCMT--SRTVAVG--SSGLMIALTVSSPTLSR-------SAFLKRCEFPG------------------------VAAKDLYIGSMITVYSRQLKIVEY--
>UniRef100_A0A7R8V793 DM10 domain-containing protein n=1 Tax=Hermetia illucens TaxID=343691 RepID=A0A7R8V793_HERIL
-RLVFLGEWFQEE--ASMSRDFSIFYYPSDSAVEIFDLKTK-------KTFLKRTRVDY------------------------LSESDFFIGARVNIFGRQITILDY--
>UniRef100_A0A7S2BU91 DM10 domain-containing protein n=1 Tax=Florenciella parvula TaxID=236787 RepID=A0A7S2BU91_9STRA
-VLGFIGEWYDAV--PMLTRKFLIKIFVESNSIEIYHVGSgpS-------KCFLRKSPLQsD------------------------LSVDSFNVGEKVLINSRLINLVDY--
>UniRef100_A0A7S4A4J2 Nucleoside diphosphate kinase-like domain-containing protein n=1 Tax=Pelagomonas calceolata TaxID=35677 RepID=A0A7S4A4J2_9STRA
-ILAYQCTTYDAR--AQLAREIRLN-SFADGTIELLNKDRT-------KTIMKRIWCPD------------------------VPRSRLFPGSTVDVFGKALEVVCA--
>UniRef100_A0A836KK81 DM10 domain-containing protein n=1 Tax=Leishmania enriettii TaxID=5663 RepID=A0A836KK81_LEIEN
-RMAFHAQQQDPG--APQPRQLILRYFHQSGTVELMEVPSG-------RLYLKRTAI-D------------------------LPASAFTVGSTVMLFGKATVITAF--
>UniRef100_A0A8J8NMD4 DM10 domain-containing protein n=1 Tax=Halteria grandinella TaxID=5974 RepID=A0A8J8NMD4_HALGN
-SIAFLVNWFDKL--ASIERPYRFIYYPYDQSIEIIDLKTR-------KQALKRIKQDA------------------------IRQEDLFVGNYLDIYGKRYKITDY--
>UniRef100_A0A8S1DV32 DM10 domain-containing protein n=1 Tax=Cloeon dipterum TaxID=197152 RepID=A0A8S1DV32_9INSE
-NLAFEADWFDEE--SGLNRTFKMIYFPESNMVQLFEPRTN-------KMFLKKSSVAG------------------------LKPSDIYVGSEITILSRQFRLKAF--
>UniRef100_A0A9D4ZIW6 Uncharacterized protein n=1 Tax=Adiantum capillus-veneris TaxID=13818 RepID=A0A9D4ZIW6_ADICA
-RFAFIVRWLDPK--TLLIWHYQLFYYTHDQSVEMFDIKNQ-------RIFLKRVSHPE------------------------IHLEHLYIGASISLYSRQLIIESY--
>UniRef100_D8LIS4 Nucleoside diphosphate kinase 7 isoform a n=1 Tax=Ectocarpus siliculosus TaxID=2880 RepID=D8LIS4_ECTSI
-PVGFSVEYFDPV--AKSLRSFVLT-VFPDRKVQM--VCGN-------KTFLSKTYAKD------------------------LVTTDLYIGGTVVLFSRELSIVDY--
>UniRef100_E0V8Z4 Nucleoside diphosphate kinase, putative n=1 Tax=Pediculus humanus subsp. corporis TaxID=121224 RepID=E0V8Z4_PEDHC
-KYMFIVEWYDPV--AQIIKKFLMTFYPAENSVELYDLIHQ-------RTFLRKSKQEG------------------------MNLENLYKSAIVTVMSRQMKIVDY--
>UniRef100_G0UKZ6 Putative nucleoside diphosphate kinase n=1 Tax=Trypanosoma congolense (strain IL3000) TaxID=1068625 RepID=G0UKZ6_TRYCI
-HLSFFCEQYDHI--AHRTNRYVLQFYFEDHTVEMRQVSNS-------KLHLKRAPFPH------------------------LSRENFKLGNSLSLLGGVVKLVSY--
>UniRef100_S9VPU5 Nucleoside-diphosphate kinase n=2 Tax=Strigomonas culicis TaxID=28005 RepID=S9VPU5_9TRYP
-RMTFECEQYDQY--ASLRRLYVLFFFYNDGTVEMIDRTND-------KVYLKRTPT-A------------------------IPRNAFFLGATVNVLGKPTTITGY--
>UniRef100_UPI001402CD31 nucleoside diphosphate kinase 7 n=1 Tax=Petromyzon marinus TaxID=7757 RepID=UPI001402CD31
-RWCFMAEWLDPL--AGITRKFSFRYFPHDRSVEMLELRTQ-------RLFLRRSPCQG------------------------LAPSQVALGARLLVLGRELSLTAY--
>UniRef100_UPI001C4C8BB4 nucleoside diphosphate kinase 7-like n=1 Tax=Sceloporus undulatus TaxID=8520 RepID=UPI001C4C8BB4
-SETESVDMLGTA--TDPEEEEIQS-HTSQRQIRY-DMKNR-------CRFLNRTKYED------------------------LHFKDLFVGNKITIYSRHLNLVDY--
>UniRef100_UPI00214811F2 nucleoside diphosphate kinase 7-like n=1 Tax=Aethina tumida TaxID=116153 RepID=UPI00214811F2
-KLSFVAEWHHQE--NIII--LTLNFYPIDGTLELLDPHGH-------KCFLKRTKIKN------------------------IELKDVYPCTTLVIFGRMIRVVDY--
>UniRef100_UPI002148D1AD nucleoside diphosphate kinase 7 n=1 Tax=Aethina tumida TaxID=116153 RepID=UPI002148D1AD
-KLSFIAEWKSGI--GD--RHFIFHYFPFDKTIQLYDKDKN-------YLYLRRIKTK-------------------------VRYIDLYPGNKLMIFGKLMTLTDF--
>UniRef100_A0A7S1U9B2 Calmodulin n=2 Tax=Phaeomonas parva TaxID=124430 RepID=A0A7S1U9B2_9STRA
EVFRFFGYIDETVTEGGvvevrRIKEVTLLYFLTDHTWQVEAVAAGDAGIAG-GLLLRRTKVPQPDGG----------------VGEYLKLNDVRVGEPLRIFGLNMNITDADE
>UniRef100_A0A7R9HVS4 DM10 domain-containing protein n=1 Tax=Timema bartmani TaxID=61472 RepID=A0A7R9HVS4_9NEOP
---SFLVDWDDED--ASLVRKFQLLYYLEDDTIELYELRKNKGAR-P-RLFLKRTRVAA------------------------VNLGAMHVGSTFNVMGRNMRISDF--
>UniRef100_A0A2R5G4U5 EF-hand domain-containing protein 1 n=1 Tax=Hondaea fermentalgiana TaxID=2315210 RepID=A0A2R5G4U5_9STRA
-VLRFFTFFREPVFesalETFRIRRCELLYFLENGDVAVNEPKEQNSGLPQ-GVLVKRMPLTHED-------------------GSTFDPTEFCIGQELSIFRVRYRIVDVDE
>UniRef100_A0A8X6PF62 EF-hand domain-containing family member C2 n=1 Tax=Nephila pilipes TaxID=299642 RepID=A0A8X6PF62_NEPPI
-----------------RCRECNVMYFLDDDEMKIYEPPQLNSGLPQGNkTVLDNLVINKSSNFIEAKMCsdyDCVFQfymvfslyVlgcivgkgkFIKPEGGFYTIDDLNIGKSLFVNGKEFKIINCDS
>UniRef100_UPI001FB6296C EF-hand domain-containing family member C2-like n=1 Tax=Penaeus chinensis TaxID=139456 RepID=UPI001FB6296C
KILSFGGVLLDG--NTGGQREVRLYYHLEDHTVRVVETPTANAGTIQG-TLVGRQRVSLSTHP----------------LSTHLDLSHFKVGETVTILGRTYFLTSCDP
>UniRef100_D7FN34 DM10 domain-containing protein n=1 Tax=Ectocarpus siliculosus TaxID=2880 RepID=D7FN34_ECTSI
-TLRFQVVWDDPS-VGGTRKRYDLLLFLEDETVSLHNPKEerQNSGSDESVIHARRQRLPKDWTTRTdvnSGGEGG-QADDGNAGGGFVGELDLAVGRSVYVWGREMKMVGCDP
>UniRef100_A0A8J5XPG3 Calmodulin n=1 Tax=Diacronema lutheri TaxID=2081491 RepID=A0A8J5XPG3_DIALT
-VLRYYLVWDEG-PPHNCQRQLELRYFLADGTAELHEDRASharaRRGFDTLPFVVGRTRIPLKYTQAS----AASFGVP--SEARTLSPADLQIGAVVDVFGRKCTVHDADA
>UniRef100_A0A2V0P427 DM10 domain-containing protein n=1 Tax=Raphidocelis subcapitata TaxID=307507 RepID=A0A2V0P427_9CHLO
----------------GELLPLVVRHYLEDGTFEVAEVLPKKGGKDPFPRMLQRGRLPRALPAAG-CRPAAAHervaaSRRAAASGEHYGADDLRIGAVINVYNRPVLLTGMDD
>UniRef100_A0A836CMK0 DM10 domain-containing protein n=1 Tax=Tribonema minus TaxID=303371 RepID=A0A836CMK0_9STRA
RVLRWYGVIREEFahTpraRETRTRAVTVLYYCQDETLEVYEPRARAPGGLGG-SLVKRARVPRWDPAAAAA---AAAAAGAGAAPAAITPADIAVGAELVVYGTPILITGCDA
>UniRef100_A0A1W0WCH1 EF-hand domain-containing protein 1 n=1 Tax=Hypsibius dujardini TaxID=232323 RepID=A0A1W0WCH1_HYPDU
--LLFVGIVDDTMCPMARLRPVVVEqhsvsdpnfsisspttalcgnvvhadivdqlqlvatdksnakYYLVDETMKIVEFRIGNDAHQFGsalNTVIRRGRIPMGIVEQNMQF---GLGPFhKPYITEFYNPTDLVVGNTLFLYGQKILLVEANE
>UniRef100_A0A6U9QV95 DM10 domain-containing protein n=1 Tax=Picocystis salinarum TaxID=88271 RepID=A0A6U9QV95_9CHLO
QVLRFFATAEES----NETRFFILYFYLVDDTVQVEICQDSKGSRPHVP-FINRHIATDGLT------------------GNTISFSSLQVGDRVEIFKHVFQLCACDA
>UniRef100_A0A2R5G4U5 EF-hand domain-containing protein 1 n=1 Tax=Hondaea fermentalgiana TaxID=2315210 RepID=A0A2R5G4U5_9STRA
-TLRISCVWDDSSRLYGDKHFFQLNYYLADDTIAIYEVGVA-------STLYKRSKLLVDKEN---------------LTKGFVQPSDLVCGRYIACNGRKLLLLKC--
>UniRef100_A0A8X7BU46 EF-hand domain-containing family member C2 n=1 Tax=Trichonephila inaurata madagascariensis TaxID=2747483 RepID=A0A8X7BU46_9ARAC
KILRFLSNILTN-QPIKKHNFFVISFYLEDDTIEINKFDPdKNcdSGLG--HRHLHRMKIAKPTTNP--------LN----ANNCFYQKTDFYVGNVICANSEQHYLFDADD
>UniRef100_A0A7S0XFR9 DM10 domain-containing protein n=1 Tax=Chromulina nebulosa TaxID=96789 RepID=A0A7S0XFR9_9STRA
-TLRFYGVWDNRDHLYGDVIHVCVHYRLADDTIEIIPDHHyVNEKhlFTDMKTILKSTKIYKDRSKHQilfnpdfmnknlsinvadhitsqitnelsthsndlTSDPSTYLSPilsnnlsnelpnklkndstsqLDNEERDFYHWSDFYIGYRLQITAVDILLYDADN
>UniRef100_A0A482QWP0 DM10 domain-containing protein (Fragment) n=1 Tax=Methanosarcinales archaeon TaxID=2250255 RepID=A0A482QWP0_9EURY
--VRFKAHLVTSD-PIDRSRQFTIIYYADDKEVGVYEHSIRNSGVLAGS-FMRKTRLRNSAT------------------GEFFELDDFEVGKNVLINAFTFHVE----
>UniRef100_A0A979FTI2 EF-hand domain-containing family member C2 n=1 Tax=Hyalella azteca TaxID=294128 RepID=A0A979FTI2_HYAAZ
DSLHPGLQPSSDdrVHAGLDDRQYTLLLYTEDNSAVLLQQPAHNTGSYSGRKVLSRQRIPLIHD-----------------PSTYVTPECLQADNIIYISGRQYRVQGCDT
>UniRef100_A0A1D1VG96 DM10 domain-containing protein n=1 Tax=Ramazzottius varieornatus TaxID=947166 RepID=A0A1D1VG96_RAMVA
-CLRYYGYYVERLfggdvsyQDYGyRVRQVELVYHMEDDTITVFEPYLENSGLPQGPTCPRRP-YYWPDS--------------DCTRKKAYFWTDLHLGCDYQIAHFKIHLYDADD
>UniRef100_F0YE10 DM10 domain-containing protein n=1 Tax=Aureococcus anophagefferens TaxID=44056 RepID=F0YE10_AURAN
-VLRFAAYFTESTEwafsgelgkPSdrgVQVRKCFVLFHLEDGTVEVLEERTSNSGVAGGR-FFNRAPPGAAGMGW-KTQPAPGL-----GAPSTAGPEGLEVGGELVFLGQTFYLVDADG
>UniRef100_A0A482UPT1 DM10 domain-containing protein n=1 Tax=archaeon TaxID=1906665 RepID=A0A482UPT1_9ARCH
-ILNFTAYFEETLpsSPDPLIRSCNIFFYTEDGSLKVVEKPQANAGVTQG-TLVKRGVILKSNG-------------------TPVMEEDFRPGQGLMIFARHY-------
>UniRef100_UPI001886DD00 nucleoside diphosphate kinase 7-like n=1 Tax=Rhipicephalus microplus TaxID=6941 RepID=UPI001886DD00
---NAAAA-TGF--GCYSGAQVHLPPLQPDSALVSskapplsplge-ELKTR-------RVFLRRTECE------------------------SCSLRDLFWGNVVAVLSRHLRILG---
>UniRef100_UPI0015B1F9FA EF-hand domain-containing family member C2-like n=1 Tax=Stegodyphus dumicola TaxID=202533 RepID=UPI0015B1F9FA
KMLRFYGIWEDNKVPKDKKLYIILLVSLTDGTFKIIEDRELDSRSYDSRLVLKPSLIPKVHISSVAVFAKdinvvMCLNWREtnsyrfrVKPEEFLTELDLDLGMFFNMYGYQLFLYDCDA
>UniRef100_UPI001FB6296C EF-hand domain-containing family member C2-like n=1 Tax=Penaeus chinensis TaxID=139456 RepID=UPI001FB6296C
QVLRYFGEWVAEGKEGGGVRtlvtdRVELRYYLEDDTAEVRVHHLTPqqdvltPARPaQPTKILKRGPVAKNIAELNnaSSLgsvGRPTLNLVGlrggrahlkdrrpqaPCSPVFLQPKDLVLGKTVDVAGRLLRLCECDS
>UniRef100_A0A1D1V9F0 DM10 domain-containing protein n=1 Tax=Ramazzottius varieornatus TaxID=947166 RepID=A0A1D1V9F0_RAMVA
NSLVFSVKMITDD-AIDGSRNFIMTYSLNDDGVCVKERVGAGRRNLRccSDLYLPP-------------------------------------------------------
>UniRef100_UPI001C719FF3 EF-hand domain-containing family member C2-like n=1 Tax=Parasteatoda tepidariorum TaxID=114398 RepID=UPI001C719FF3
---KFFARAITE-DPVEKLHRFVVCFFLEDNTLSIIILDNHhDSSL-ELP-RFRRMKVTKPQSI------------HENSGRCFYRPLDMYVGNVIYVRGKPFELLEADD
>UniRef100_A0A7G2CDL7 DUF1126 PH-like domain containing protein, putative n=1 Tax=Angomonas deanei TaxID=59799 RepID=A0A7G2CDL7_9TRYP
EVLRFRLKLANPTDNNQAMRRFVLSYYTDTEEGMVHEVALPNLGFPA-GLLLKRGVLPKPEQKMT--VRQATLSSAhdnqqIIQEVNRYKEEDIAIGSELVLAGMPMKVVGMDA
>UniRef100_A0A1D2A456 DM10 domain-containing protein (Fragment) n=1 Tax=Auxenochlorella protothecoides TaxID=3075 RepID=A0A1D2A456_AUXPR
----------------RKGGRGTVS-------------SRTPACGAPHP-LHARLSSYHLL-----------------PSQTLISEKDIWVGAVIPLAGRRFELLAADN
>UniRef100_A0A7S1U9B2 Calmodulin n=2 Tax=Phaeomonas parva TaxID=124430 RepID=A0A7S1U9B2_9STRA
-------------------AWYKVYFYYQNDTVEIRHHA-TNS------LVLKRGRLPKDGSNYVPTGYSGSLNNSSDDGVPFVDLSDLRVGRFLNVYGRRLLVAQTD-
>UniRef100_A0A1D1VG96 DM10 domain-containing protein n=1 Tax=Ramazzottius varieornatus TaxID=947166 RepID=A0A1D1VG96_RAMVA
-IIKYTAKLYSRH-PDAQIPTYVILYYVADDTMAVYEKLVHGDASY-GKKFMKRQKFRIPELQ-KDPFERTV------NPGPYYNFRDLLPGNLLNLNGSRLLLIAPDE
>UniRef100_A0A1I7U0V3 DM10 domain-containing protein n=1 Tax=Caenorhabditis tropicalis TaxID=1561998 RepID=A0A1I7U0V3_9PELO
-MLVYRCCWLDHMNDFhGcrMKRIFKMFVYCTDHTVALIEETK---EFEGQ-LFLKRIALPFPVEP--------------EMPRRDYRWWDIRPGVWVDVFCRPMFVFECA-
>UniRef100_A0A7S3GX31 DM10 domain-containing protein n=1 Tax=Spumella elongata TaxID=89044 RepID=A0A7S3GX31_9STRA
----------------GDVKRFALSYHLSTCNIDLvvqKEIGKPDAGQDEPKLVLKKSKLPVNWRDAQRG-----------RPAHFYEPHDFSCGKVIDVYGRYFLLVNCDK
>UniRef100_A0A2S2QEL0 EF-hand domain-containing family member C2 n=1 Tax=Sipha flava TaxID=143950 RepID=A0A2S2QEL0_9HEMI
-ALVFKANIVPK-EPNNLNREFVIKYFLNDQSFSVSEMKTQTAGALGCR-FFSKRKIPMETPN---------------ESSMIL---KLYIGAKLVIDNFQFVLVDIED
>UniRef100_UPI0021AA34F9 EF-hand domain-containing family member C2-like n=1 Tax=Daktulosphaira vitifoliae TaxID=58002 RepID=UPI0021AA34F9
-VFIFKAKMVSN-DPINLSRHFLLKYFFNSNTFGIYEITEPNSGVIGGE-FRSKRSISIFDEN---------------EKSFIYS--EIAVGSKLFIDDFQFVLTDVDD
>UniRef100_A0A423TJM5 Putative EF-hand domain-containing family member C2 n=1 Tax=Penaeus vannamei TaxID=6689 RepID=A0A423TJM5_PENVA
----YFGEWVAEGKESGGVrtlvtDKVELRYYLEDDTAEVRVHHLTpqqdvltpARPAQP-TKILKRGPVAKNMAELNNaSslgsVGRPTLNLVGlrggrahlkdrrpqaPSSPVFLQPKDLVLGKTVDVAGRLLRLCECDS
>UniRef100_A0A7S4D4E8 DM10 domain-containing protein n=1 Tax=Heterosigma akashiwo TaxID=2829 RepID=A0A7S4D4E8_HETAK
--LVFFLRWQDRGLP---EKYYKAAFWPSDGTMEVRELGLE--GYAIYAVLLRRQRVRKEAAPTRV----DAIGhGSSGGVQNYVTLSDLRVGHPLYVQGRAMQVVAA--
>UniRef100_A0A0M0K4M2 DM10 domain-containing protein n=1 Tax=Chrysochromulina tobinii TaxID=1460289 RepID=A0A0M0K4M2_9EUKA
---------------AGEPRHFFLAFFLADDTLQVHEVFGAdverLSGGGAGpagtrperVALLRRLRAPNRES-----------------ASGFVELRDLRIGAVVPIQGVPLRLVACE-
>UniRef100_A0A146M5Q1 EF-hand domain-containing protein 1 (Fragment) n=1 Tax=Lygus hesperus TaxID=30085 RepID=A0A146M5Q1_LYGHE
--FRFVACLANAAEEAEAQRRFIVCFYLSDYTVAMAELTPVNGGSTVSKTFSRRAVA------------------------SLHDPDVLRIGNVVTLDGLAYQLLDMDE
>UniRef100_R4V3D4 EF-hand domain-containing protein (Fragment) n=1 Tax=Coptotermes formosanus TaxID=36987 RepID=R4V3D4_COPFO
-TLHFIASWNDATNPFFDQRSFILIYFVDTNEFEVRQRKV-LSGQVS-RLFL-RNSVRKQD-------------------GTLYGLKDLRMKSGITIQGKNFIILDAD-
>UniRef100_A0A0H5QI73 DM10 domain-containing protein (Fragment) n=1 Tax=Spongospora subterranea TaxID=70186 RepID=A0A0H5QI73_9EUKA
-------------------PLCVLRYFTCDDTMEVVLDKqQRLLGEDFCRTVVSRRRWPKDQRST-----SSSLTDFAsenqDVNSSFIRSEDLSPGKILIAFGRRFLIIRADP
>UniRef100_U6MV68 Nucleoside diphosphate kinase 7, putative n=1 Tax=Eimeria necatrix TaxID=51315 RepID=U6MV68_9EIME
-RLAFYASWDAS--GAGDTKELILVYYTSDSTIELKSSSSSSSSS---STNLKRVLVPKATI------------------------QNLYQGAQLVLFSRHLRILE---
>UniRef100_A2DHM4 RIB72 protein, putative n=1 Tax=Trichomonas vaginalis (strain ATCC PRA-98 / G3) TaxID=412133 RepID=A2DHM4_TRIV3
-ELRFLAKMISK-NPDNDKREFSVIFSLVNDEVKVWENKT--DGFDGGFVYKAPHIRPKAP--------------------P--HYNDMYIGANVEINHVVYKLYGA--
>UniRef100_A0A7R9APX6 DM10 domain-containing protein n=1 Tax=Timema shepardi TaxID=629360 RepID=A0A7R9APX6_TIMSH
---------------------VVLSSTAEDGEIEVRISVgivtKLSVGFHY-GSFISRRKIFRPNQD-----------LFGSEAPECYDHEDFYIGNILELHGFRFRLVDADE
>UniRef100_A0A8J2AZZ6 DM10 domain-containing protein n=1 Tax=Amoebophrya sp. A120 TaxID=2202890 RepID=A0A8J2AZZ6_9DINO
------------------RQYFTILFHTEDSTIEIMRQPTGNTYPVgkttaeGKSLYHSRAAVPRSQLA---SSARCMVTRvgIAPSPGELVQAEDLQTGSSVILYGEEFHLYDCDE
>UniRef100_A0A0H5QI73 DM10 domain-containing protein (Fragment) n=1 Tax=Spongospora subterranea TaxID=70186 RepID=A0A0H5QI73_9EUKA
-VLRFLAELESNR--NATDSRFIIEYRSDDESVTIYEKKS-KSGSAA-KKFLERTVEHKG---------------------DEFRLEDLRVGRTCVINKFRFVVVEED-
>UniRef100_UPI0018A77B71 EF-hand domain-containing protein 1-like n=1 Tax=Penaeus monodon TaxID=6687 RepID=UPI0018A77B71
-VLKFDAMVEESEGGRPAASPAVVLYRPEDKTVELRRPSHLDhTEIKkFSPVILRAVRVPKYDTRK-AGF----VDIGEEeQMEVWLTPRDLAPPTSVTIFGRRVMVTGCDD
>UniRef100_A0A7S2CE11 DM10 domain-containing protein (Fragment) n=1 Tax=Haptolina brevifila TaxID=156173 RepID=A0A7S2CE11_9EUKA
-----------------------LTYYLADNTLEVHQLLLPGEGCKAEQLLLRRGFVPRQEHAVGtSGIPGraTSIEddgslhirggtshrasshmgGSSrpprssshlERSSSHLELADLTVGAELHIASLPMRIVA---
>UniRef100_A0A1D1UNY3 DM10 domain-containing protein n=1 Tax=Ramazzottius varieornatus TaxID=947166 RepID=A0A1D1UNY3_RAMVA
--------------KQDSERNFVMSFSLSDDGIFVYEKNVPP-GATPGT-Y-RGNRAMKKMND------------PITDQPVYVTAEDLYVGAVFEFSKRTFVITEVDD
>UniRef100_A2DP64 RIB72 protein, putative n=1 Tax=Trichomonas vaginalis (strain ATCC PRA-98 / G3) TaxID=412133 RepID=A2DP64_TRIV3
----FQSKLITP-NQEDKQRIFLLTYFVNTKEISIQEGRSPCTSQA-HP-YYSRGKITNPA------------------VQGPYEPKDFYVGSTITALGRKFYLTDAS-
>UniRef100_UPI0021E5B376 EF-hand domain-containing family n=1 Tax=Trichomonas vaginalis (strain ATCC PRA-98 / G3) TaxID=412133 RepID=UPI0021E5B376
----FQSKLITP-NQEDKQRIFLLTYFVNTKEISIQKADLHALHK--HT-HTIHAVKSQIQ------------------QSKDHTSPKISMCSTITALGRKFYLTDAS-
>UniRef100_A0A6I8TJZ9 Uncharacterized protein n=1 Tax=Aedes aegypti TaxID=7159 RepID=A0A6I8TJZ9_AEDAE
--MAFIGEWFKN--EAKTIQQLMVYFYPSEKAIELYETKTK-------KVFLHKTRIEE------------------------ISQSDFFIGAKLLIFGKQIVIVDY--
>UniRef100_A0A6P9BD88 Nucleoside diphosphate kinase 7 isoform X1 n=1 Tax=Pantherophis guttatus TaxID=94885 RepID=A0A6P9BD88_PANGU
--AEFLSPILHLS--CLRNKIEPQLIIISRERSELhlrirkqkYDMKNR-------CKFLNRTKYED------------------------LNFKDLFVGNRITIFSRHLNLVDY--
>UniRef100_A0A024GSX1 DM10 domain-containing protein n=1 Tax=Albugo candida TaxID=65357 RepID=A0A024GSX1_9STRA
-KLSYFAEWHDPQ--SDQDKQYILNCFP-DQTLELIERQNK-------RIFLKKIRIPT------------------------VSTPDINVGATITVYSRQFRIIAT--
>UniRef100_A0A7S2Y0S4 DM10 domain-containing protein (Fragment) n=1 Tax=Fibrocapsa japonica TaxID=94617 RepID=A0A7S2Y0S4_9STRA
EVLAFVAEWFDPM--PQLTKTYLLKFFPETHEVEMVDAKSR-------RLFLKRSKCPDT-----------------------ILKEEFFVGSQMVLYARHLSLVDY--
>UniRef100_UPI000E6E3502 nucleoside diphosphate kinase 7-like n=1 Tax=Ctenocephalides felis TaxID=7515 RepID=UPI000E6E3502
---AFNTEWYDPT--SRLRRKFIVSYYPADETVAMWDKTFK-------KKFLQRMNVG-------------------------LKSEDFFVGNRITLNFRPMYIVSY--
>UniRef100_A0A0F7UCV2 EF-hand domain-containing protein 1, related n=1 Tax=Neospora caninum (strain Liverpool) TaxID=572307 RepID=A0A0F7UCV2_NEOCL
-GFPVIGIDTLPHGKhrqkPRklkcSAGPFILNLWASDSPVEVGEVRTKAAEHRgrDG-GFQKLSAHENDEA------------------AEGCTLSGSWWTHATP--ERHFLSIGPEN
>UniRef100_A0A7R9VYI6 DM10 domain-containing protein n=1 Tax=Chlamydomonas euryale TaxID=1486919 RepID=A0A7R9VYI6_9CHLO
--LFFEAQWEDPT--NGVTWRFELFYYPETNEVEMVDVQNL-------KTYVKMSD-------------------------VAIRPDMLQVGAEVKVYNKKLTILRY--
>UniRef100_A0A835YVB6 DM10 domain-containing protein n=1 Tax=Tribonema minus TaxID=303371 RepID=A0A835YVB6_9STRA
---------------YQAVRSLKLFYYP-DGCLELIECENK-------KTFLSKTFVE------------------------AVQPQDLYVGSTLEVFSRLVHLVGY--
>UniRef100_A0A0F7UCV2 EF-hand domain-containing protein 1, related n=1 Tax=Neospora caninum (strain Liverpool) TaxID=572307 RepID=A0A0F7UCV2_NEOCL
AAAKAQSVWEKPG-LLLSLSKSVLSH--GSSLREALPSAIFQNREREMP---------------------------------TVRRAGFALLDWVVAPPRGLASFSCA-
>UniRef100_A0A976FG98 DM10 domain-containing protein n=1 Tax=Bremia lactucae TaxID=4779 RepID=A0A976FG98_BRELC
-VYSFKARSFDMH--AQLYRQYDLRYFVTSHHLKIVDTKTS-------RVFLRKSECPAA-----------------------LSAKDFYVGANVFIYDRYFELLDY--
>UniRef100_A0A177B749 DM10 domain-containing protein n=1 Tax=Intoshia linei TaxID=1819745 RepID=A0A177B749_9BILA
-RFCFKAEWYEDL--SETYKPFNLLYYPADDTIELNQTNLR-------KTFLSRSKCRN------------------------ISMDDLFIGNTINIYCRNFKILEY--
>UniRef100_A0A1J4JL88 Nucleoside diphosphate kinase n=1 Tax=Tritrichomonas foetus TaxID=1144522 RepID=A0A1J4JL88_9EUKA
-SYAFKIEFFDEM--AELVRPYVLTYHTEKGEIELFDIRNR-------RPFLKRTDNHT------------------------IQKKDLFIGNKILVNGRQYEIVEF--
>UniRef100_A0A1J4K1V1 Nucleoside diphosphate kinase n=1 Tax=Tritrichomonas foetus TaxID=1144522 RepID=A0A1J4K1V1_9EUKA
-VYSFKLEYFDEP--AELVRPYYLTYRTERGEIEIFDIRNH-------RPFLKRTVLHN------------------------IQIKDLYVGNKLLINGRQYDVVDI--
>UniRef100_A0A2I0TX98 DM10 domain-containing protein n=1 Tax=Limosa lapponica baueri TaxID=1758121 RepID=A0A2I0TX98_LIMLA
-DSAFTEEDEQKP--RMKLSMSPIVLSHLGDCCphgslehtgERYDVKNH-------RTFLKRTKYES------------------------LHLEDLFVGNKITVFSRHLSLVDY--
>UniRef100_A0A553NP03 Nucleoside diphosphate kinase n=1 Tax=Tigriopus californicus TaxID=6832 RepID=A0A553NP03_TIGCA
-SFTFTVNWYDQT--MDKDRKFKLTFFPRDNSVEMFDIKHQ-------RVFLKRIVCDG------------------------LHVGDFFVGNHVVVLARRLQVLEY--
>UniRef100_A0A7D9IHU3 Nucleoside diphosphate kinase 7-like n=2 Tax=Paramuricea clavata TaxID=317549 RepID=A0A7D9IHU3_PARCT
---MSKSEETRQN--VEESLHGDLMSVVSILYFCDFDIKNK-------RVFLKRSKCEG------------------------IRLHDLHIGAVVNIHSRQLTIKDY--
>UniRef100_A0A7S0AMD1 Nucleoside diphosphate kinase-like domain-containing protein n=1 Tax=Pyrodinium bahamense TaxID=73915 RepID=A0A7S0AMD1_9DINO
-QYKFRCEHYEEH--SQMCKEFILTMFvKSARGPhELslFDIKNN-------RVFLKRGVYeqdGP------------------------LRLQDLHVNGSVTVCSRKLKILEY--
>UniRef100_A0A7S0JR10 DM10 domain-containing protein n=2 Tax=Cafeteria roenbergensis TaxID=33653 RepID=A0A7S0JR10_CAFRO
-QYSFGCELLDPI--TNTLRPYNIAMWPFDASVEVYDPTSR-------RTILKRCRPrES------------------------ISVDDFFLGNTITVMSRPYVVRKY--
>UniRef100_A0A7S2VQ30 DM10 domain-containing protein n=1 Tax=Brandtodinium nutricula TaxID=1333877 RepID=A0A7S2VQ30_9DINO
-AYGFNVDWFDETG-GALTRRYVATVYaPDRGPVevSMYDPTSK-------RAFLKRTPVPG------------------------LALEDFSIGSEVTVMTRTLKVRGY--
>UniRef100_A0A8S4GXG9 Nucleoside diphosphate kinase n=1 Tax=Pedinophyceae sp. YPF-701 TaxID=765719 RepID=A0A8S4GXG9_9CHLO
-SYNFKAAWLDPV--SGVEWSFLFTYHRETAKVELYDVKNR-------RAYLKPALLptGP------------------------IPDDRFFLGAKLMIFGRSLELVDF--
>UniRef100_UPI00071E4DBC nucleoside diphosphate kinase 7 n=1 Tax=Octopus bimaculoides TaxID=37653 RepID=UPI00071E4DBC
-RYCFVVDWYDAV--ASLTRRYQFLYYPKDKSVEMVSIIKS-------NEFIGEKTEfmdkrnrnKP------------------------TTLCNSWCGGGGGRETVDvdilftfsfypcnpnskypvtdgylacnvkssafngwlesklfdQTCLHL--
kensch@kbf-linux01:~$ #Filter "EFHC1_Hs_222_330.a3m" alignment to include only the 30 most diverse sequences.
kensch@kbf-linux01:~$
hhfilter -i "/home/kensch/Alignments/A3M files/DM10/EFHC1_Hs_222_330.a3m" -o query.fil.a3m -diff 30
- 15:44:42.834 INFO: Input file = /home/kensch/Alignments/A3M files/DM10/EFHC1_Hs_222_330.a3m

- 15:44:42.834 INFO: Output file = query.fil.a3m

kensch@kbf-linux01:~$ #Trim edges of filtered alignment and make trimmed alignment fasta format.
kensch@kbf-linux01:~$ /home/kensch/hh-suite/scripts/reformat.pl -r query.fil.a3m query.fil.fas
Reformatted query.fil.a3m with 36 sequences from a3m to fas and written to file query.fil.fas
kensch@kbf-linux01:~$ #Save filtered, trimmed algnment as "DM10/EFHC1_filtered30_trimmed.fas".
kensch@kbf-linux01:~$ mv query.fil.fas "/home/kensch/Alignments/A3M files/DM10/EFHC1_filtered30_trimmed.fas"

#Show alignment of filtered, trimmed, and curated EFHC1_DM10 query alignment.
cat "/home/kensch/Alignments/A3M files/DM10/"
